//! The D13 error registry, as JSON-RPC (design D10, D13).
//!
//! One home for the mapping, in both directions: a [`schema::Error`] becomes an
//! [`ErrorObjectOwned`] the daemon returns, and an [`ErrorObject`] a client receives
//! becomes a [`schema::Error`] again. `wchc` therefore renders exactly what `wch` renders,
//! because it renders the *same value* through the same `Display` — which is what P4f's
//! parity gate is going to compare byte for byte.
//!
//! ## Why the match is over [`ErrorKind`] and not over [`schema::Error`]
//!
//! `schema::Error` is `#[non_exhaustive]`. That attribute binds *downstream* crates, and
//! this crate is downstream of `webcam-handler-schema`, so a `match` on the error itself
//! would need a wildcard arm here — and a wildcard is precisely the thing D13 exists to
//! forbid: with one, a twentieth variant compiles silently and reaches the wire as
//! somebody else's code. [`ErrorKind`] carries no such attribute and is generated by
//! `closed_vocabulary!` together with its `ALL`, so [`rpc_code`]'s match is
//! compiler-enforced: a twentieth variant does not build until it has a code, and P4d's
//! deletion of `Unimplemented` does not build until its arm goes (which is the mechanism
//! note N6 names for its own retirement).
//!
//! Do not "simplify" that dependence away. The compile-time guarantee comes from the
//! kind, not from the error.

use std::fmt;
use std::ops::RangeInclusive;

use jsonrpsee::types::{ErrorObject, ErrorObjectOwned};
use schema::error::{Error, ErrorKind};

/// JSON-RPC 2.0's band for implementation-defined server errors.
///
/// The specification reserves `-32768 ..= -32000` and gives `-32099 ..= -32000` to the
/// implementation; everything outside the reserved block belongs to the application. D13's
/// codes are *this server's* answers about a device, which is what the implementation-
/// defined band is for, so they live inside it and [`D13_CODES`] is the part of it that is
/// ours.
pub const SERVER_ERROR_BAND: RangeInclusive<i32> = -32099..=-32000;

/// The closed range every D13 code comes from.
///
/// Stated in the accessors' terms, because this constant is `pub` and a reader will call
/// them: `D13_CODES.end()` is `-32012` and `D13_CODES.start()` is `-32030`.
///
/// **The range ends at `-32012` because that is the first code below the transport's
/// lowest reserved constant, and D13 wants one unbroken block.** Measured against the
/// pinned jsonrpsee 0.26.0 (`jsonrpsee-types-0.26.0/src/error.rs`), the transport owns
/// `-32000` (call execution failed), `-32001` (unknown error) and `-32005 ..= -32011`
/// (batches unsupported, too many subscriptions, oversized request, oversized response,
/// server busy, batch request too large, batch response too large) inside
/// [`SERVER_ERROR_BAND`]. Three codes it leaves unclaimed — `-32002`, `-32003` and
/// `-32004` — sit *inside* that run, and D13 deliberately does not take them: a block with
/// holes in it is not a block, and "nineteen codes, contiguous" is a property the walk
/// below can check. So the block starts where the transport's run stops. A D13 code
/// colliding with one of the transport's would make an infrastructure failure
/// indistinguishable from a camera answer — E3's "availability is not capability" lost at
/// the transport layer — so both the collision *and* the adjacency are asserted rather
/// than assumed, and note N5's standing instruction to re-run its measurement on any
/// jsonrpsee bump covers this one too: an upstream code added at `-32012` moves this
/// block, it does not shrink it.
///
/// **The range starts at `-32030` because that is the nineteenth code, and
/// `Unimplemented` holds it deliberately.** That variant is transitional (note N6) and
/// P4d deletes it; the lowest code is the one nothing else needs, so P4d **raises
/// `start` to `-32029`** — one endpoint, no other code moves, and the other eighteen stay
/// byte-identical. A code is a compatibility contract in the same way a serde field name
/// is (rubric B1): the wire value a deployed client already knows must not change under
/// it.
pub const D13_CODES: RangeInclusive<i32> = -32030..=-32012;

/// The JSON-RPC code a D13 error crosses the wire as.
///
/// Every arm is an explicit literal. Deriving the code from the variant's ordinal —
/// `BASE + kind as i32`, or an index into `ALL` — would look correct and pass every test
/// here, because `Unimplemented` is declared last and P4d removes the last ordinal. The
/// defect that hides is the *next* change: inserting a variant anywhere but the end
/// renumbers every code below it, deployed clients start reading `StorageIo` where the
/// server sent `DeviceIo`, and nothing goes red — the walk still finds distinct codes in
/// range and the documents still round-trip. Literals make an insertion a code somebody
/// has to choose.
#[must_use]
pub const fn rpc_code(kind: ErrorKind) -> i32 {
    match kind {
        ErrorKind::DeviceGone => -32012,
        ErrorKind::Busy => -32013,
        ErrorKind::PermissionDenied => -32014,
        ErrorKind::CameraUnknown => -32015,
        ErrorKind::CameraAmbiguous => -32016,
        ErrorKind::ControlUnknown => -32017,
        ErrorKind::ControlReadOnly => -32018,
        ErrorKind::ControlInactive => -32019,
        ErrorKind::FormatUnsupported => -32020,
        ErrorKind::SettleTimeout => -32021,
        ErrorKind::FingerprintMismatch => -32022,
        ErrorKind::SessionConflict => -32023,
        ErrorKind::IllegalTransition => -32024,
        ErrorKind::SchemaVersionForeign => -32025,
        ErrorKind::StoreLocked => -32026,
        ErrorKind::HolderGone => -32027,
        ErrorKind::DeviceIo => -32028,
        ErrorKind::StorageIo => -32029,
        // The lowest code in the block, which is `D13_CODES.start()`: N6 retires this
        // variant at P4d, and the block has to shrink by raising that one endpoint
        // without moving anything else.
        ErrorKind::Unimplemented => -32030,
    }
}

/// A D13 error on its way out through jsonrpsee.
///
/// A newtype, because the T5 trait's methods return `Result<T, WireError>` and jsonrpsee's
/// `IntoResponse` is implemented for `Result<T, E>` where `E: Into<ErrorObjectOwned>` —
/// which is the whole of what this type buys: `?` in the daemon's server impl, over the
/// same `schema::Error` every other layer speaks. It adds no vocabulary and no second
/// rendering; the message it carries is `Error`'s own `Display`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireError(pub Error);

impl WireError {
    /// The error itself.
    #[must_use]
    pub fn into_inner(self) -> Error {
        self.0
    }
}

impl From<Error> for WireError {
    fn from(error: Error) -> WireError {
        WireError(error)
    }
}

impl fmt::Display for WireError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Delegated, never re-worded. D13 says the CLI renders the same variants and
        // nobody stringly-matches; a second rendering here would be a second home for a
        // sentence a human reads (design §2.10).
        self.0.fmt(f)
    }
}

impl std::error::Error for WireError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        // The inner error's source, **not** the inner error. `Display` above already *is*
        // `self.0`'s, and std's contract is that a `Display` must not include what
        // `source()` will render — so returning `Some(&self.0)` would make every chain
        // printer (`anyhow`, `eyre`, `tracing`'s error field) show D13's one sentence
        // twice, which is the second home for a sentence a human reads that `Display`
        // above exists to avoid. This is the transparent relationship `thiserror` spells
        // `#[error(transparent)]`: the newtype *is* the error it wraps, so both halves
        // delegate to it.
        self.0.source()
    }
}

impl From<WireError> for ErrorObjectOwned {
    fn from(error: WireError) -> ErrorObjectOwned {
        // `code` from a closed numeric range, `message` human, `data` typed — D10's three
        // clauses, in order. `data` is the serialized `Error` itself rather than a summary
        // of it: that is what lets a client reconstruct the variant and render it the way
        // `wch` does, and it is why no `anyhow` string ever crosses this seam (rubric B6).
        ErrorObjectOwned::owned(
            rpc_code(error.0.kind()),
            error.0.to_string(),
            Some(&error.0),
        )
    }
}

/// The D13 error inside a received error object, when there is one.
///
/// The inverse of [`From<WireError> for ErrorObjectOwned`](ErrorObjectOwned), and the half
/// `wchc` needs: a typed error that arrived as JSON becomes a [`schema::Error`] again, so
/// the client renders the value rather than a transport string.
///
/// `None` is the honest answer for everything else, and "everything else" is not a corner
/// case — a JSON-RPC connection carries the transport's own failures too (method not
/// found, oversized response, a server that is not this one). **Two** things have to hold
/// before an object is treated as ours, and each rules out a different way of being wrong:
///
/// 1. `data` deserializes into a [`schema::Error`], so an object with nothing attached, or
///    with somebody else's document attached, is not coerced into a camera answer;
/// 2. the payload's own kind maps back to the code that was sent, so an object carrying
///    one of our codes over the *wrong* one of our documents — the shape a proxy that
///    rewrote a code produces — is refused rather than believed.
///
/// There is deliberately no third check on [`D13_CODES`] membership, and the reason is
/// worth stating so it is not "restored" as a defence: [`rpc_code`] is total *onto* that
/// range, so check 2 already implies it. Every transport code fails check 2 for free —
/// `-32601` can equal no `rpc_code` — and a range test in front of it would be a branch no
/// input can distinguish, which is a line the mutation floor would report as a survivor and
/// a reader would mistake for protection. `D13_CODES` is the *declaration* of the closed
/// range D13 requires, checked against `rpc_code` by this module's walk; it is not a
/// second gate on the decode path.
///
/// A malformed object never panics here. It reads as "not a typed error", which is a thing
/// a caller can say out loud — unlike a fabricated variant, which is a lie the caller
/// would then render as if the camera had said it.
#[must_use]
pub fn typed(object: &ErrorObject<'_>) -> Option<Error> {
    let data = object.data()?;
    let error: Error = serde_json::from_str(data.get()).ok()?;
    (rpc_code(error.kind()) == object.code()).then_some(error)
}

#[cfg(test)]
mod tests {
    use jsonrpsee::types::error::{
        BATCHES_NOT_SUPPORTED_CODE, CALL_EXECUTION_FAILED_CODE, INTERNAL_ERROR_CODE,
        INVALID_PARAMS_CODE, INVALID_REQUEST_CODE, METHOD_NOT_FOUND_CODE, OVERSIZED_REQUEST_CODE,
        OVERSIZED_RESPONSE_CODE, PARSE_ERROR_CODE, SERVER_IS_BUSY_CODE, TOO_BIG_BATCH_REQUEST_CODE,
        TOO_BIG_BATCH_RESPONSE_CODE, TOO_MANY_SUBSCRIPTIONS_CODE, UNKNOWN_ERROR_CODE,
    };

    use super::*;

    /// The committed `kind → code` table.
    ///
    /// A wire code is a compatibility contract, so a change to one has to be a diff a human
    /// reads rather than a test that keeps passing. The walk below compares this file
    /// against [`ErrorKind::ALL`] in both directions, so it cannot silently fall behind the
    /// registry either: a kind missing a row fails, and a row naming a kind that no longer
    /// exists fails.
    const PINNED_CODES: &str = include_str!("../fixtures/d13-rpc-codes.tsv");

    /// The pinned table, as `(kind name, code)` pairs.
    fn pinned() -> Vec<(String, i32)> {
        PINNED_CODES
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty() && !line.starts_with('#'))
            .map(|line| {
                let (name, code) = line
                    .split_once('\t')
                    .unwrap_or_else(|| panic!("{line:?} is not `kind<TAB>code`"));
                (
                    name.to_owned(),
                    code.parse()
                        .unwrap_or_else(|_| panic!("{code:?} is not a code")),
                )
            })
            .collect()
    }

    /// A kind's name as it is spelled on the wire — derived from its own serde rendering,
    /// so the table cannot pin a spelling the registry does not use.
    fn wire_name(kind: ErrorKind) -> String {
        let json = serde_json::to_string(&kind).expect("a kind serializes");
        json.trim_matches('"').to_owned()
    }

    #[test]
    fn every_kind_has_a_distinct_code_inside_the_declared_range() {
        // The population is `ErrorKind::ALL`, generated by the vocabulary macro, so this
        // walk cannot shrink when a variant is added — and the match in `rpc_code` is what
        // stops a variant being added without a code at all.
        let mut seen: std::collections::BTreeMap<i32, ErrorKind> =
            std::collections::BTreeMap::new();
        for &kind in ErrorKind::ALL {
            let code = rpc_code(kind);
            assert!(
                D13_CODES.contains(&code),
                "{kind:?} maps to {code}, outside {D13_CODES:?}"
            );
            // Distinctness is also the assertion that would notice a wildcard arm: the
            // compiler cannot tell `_ => -32030` from nineteen literals, but two kinds
            // sharing a code is exactly what a catch-all produces.
            if let Some(other) = seen.insert(code, kind) {
                panic!("{kind:?} and {other:?} share code {code}");
            }
        }
        assert_eq!(seen.len(), ErrorKind::ALL.len());

        // The range is exactly as wide as the registry: no holes, nothing reserved that
        // nobody uses. If a variant is ever deleted from the *middle* of the registry, the
        // right repair is to leave the hole and relax this line with a note — never to
        // renumber the survivors, which is a wire break no test downstream would catch.
        let span = usize::try_from(D13_CODES.end() - D13_CODES.start() + 1).expect("a small span");
        assert_eq!(span, ErrorKind::ALL.len(), "{D13_CODES:?} has holes in it");
    }

    /// Every code the pinned jsonrpsee reserves for itself.
    ///
    /// jsonrpsee reifies no population of its own, so this names its constants rather than
    /// their values: an upstream renumber moves the constant and every assertion below
    /// follows it. Note N5 already requires re-running its measurement on any jsonrpsee
    /// bump; this is the half a test can hold.
    const JSONRPSEE_CODES: &[i32] = &[
        PARSE_ERROR_CODE,
        INVALID_REQUEST_CODE,
        METHOD_NOT_FOUND_CODE,
        INVALID_PARAMS_CODE,
        INTERNAL_ERROR_CODE,
        CALL_EXECUTION_FAILED_CODE,
        UNKNOWN_ERROR_CODE,
        BATCHES_NOT_SUPPORTED_CODE,
        TOO_MANY_SUBSCRIPTIONS_CODE,
        OVERSIZED_REQUEST_CODE,
        OVERSIZED_RESPONSE_CODE,
        SERVER_IS_BUSY_CODE,
        TOO_BIG_BATCH_REQUEST_CODE,
        TOO_BIG_BATCH_RESPONSE_CODE,
    ];

    #[test]
    fn the_declared_range_sits_inside_the_json_rpc_server_band_and_collides_with_nothing() {
        // JSON-RPC 2.0 reserves `-32768 ..= -32000` and gives the *last hundred* of it to
        // the implementation. Both ends are asserted, not just the one D13 sits near: a
        // band that reached above `-32000` would be claiming codes the application layer
        // owns, and a caller could not tell one of ours from one of its own.
        assert!(
            *SERVER_ERROR_BAND.start() >= -32768,
            "{SERVER_ERROR_BAND:?}"
        );
        assert!(*SERVER_ERROR_BAND.end() <= -32000, "{SERVER_ERROR_BAND:?}");
        // And it is the implementation's whole block rather than part of it: every
        // implementation-defined code jsonrpsee uses has to be inside it, or the band is
        // describing something narrower than it claims.
        for &implementation_defined in &[
            CALL_EXECUTION_FAILED_CODE,
            UNKNOWN_ERROR_CODE,
            BATCHES_NOT_SUPPORTED_CODE,
            TOO_BIG_BATCH_RESPONSE_CODE,
        ] {
            assert!(
                SERVER_ERROR_BAND.contains(&implementation_defined),
                "{implementation_defined} is an implementation-defined code outside \
                 {SERVER_ERROR_BAND:?}"
            );
        }

        assert!(SERVER_ERROR_BAND.contains(D13_CODES.start()));
        assert!(SERVER_ERROR_BAND.contains(D13_CODES.end()));

        for &taken in JSONRPSEE_CODES {
            assert!(
                !D13_CODES.contains(&taken),
                "{taken} is jsonrpsee's and D13 claims it too: an infrastructure failure \
                 would be indistinguishable from a camera answer"
            );
        }
    }

    #[test]
    fn the_block_begins_where_the_transports_run_stops_and_unimplemented_holds_its_far_end() {
        // The stated reason for `-32012`, checked rather than asserted in prose. The
        // transport's lowest in-band constant is `-32011`, so ours is the next code down:
        // D13 wants one unbroken block, and the three codes jsonrpsee leaves unclaimed
        // (`-32002`, `-32003`, `-32004`) sit *inside* its run, where taking them would put
        // a hole in ours. Derived from the constants, so a jsonrpsee release that reserved
        // `-32012` turns this red rather than turning the collision test red one bump later.
        let lowest_transport = JSONRPSEE_CODES
            .iter()
            .copied()
            .filter(|code| SERVER_ERROR_BAND.contains(code))
            .min()
            .expect("jsonrpsee reserves something inside the band");
        assert_eq!(
            *D13_CODES.end(),
            lowest_transport - 1,
            "D13's block is no longer adjacent to the transport's run; the repair is to \
             move the block, not to leave a gap nobody documented"
        );

        // The endpoint P4d edits, pinned in the accessors' own terms — this is the
        // assertion that would have caught the doc comment when it said the range starts
        // at `-32012`. `Unimplemented` is transitional (note N6) and holds `start`, so
        // P4d raises `start` to `-32029` and no other code moves.
        assert_eq!(rpc_code(ErrorKind::Unimplemented), *D13_CODES.start());
        assert_eq!(rpc_code(ErrorKind::DeviceGone), *D13_CODES.end());
    }

    #[test]
    fn the_codes_are_the_ones_that_were_committed() {
        let pinned = pinned();
        assert_eq!(
            pinned.len(),
            ErrorKind::ALL.len(),
            "the pinned table has {} rows for {} kinds",
            pinned.len(),
            ErrorKind::ALL.len()
        );
        for &kind in ErrorKind::ALL {
            let name = wire_name(kind);
            let (_, code) = pinned
                .iter()
                .find(|(pinned_name, _)| *pinned_name == name)
                .unwrap_or_else(|| panic!("{name} has no row in fixtures/d13-rpc-codes.tsv"));
            assert_eq!(
                rpc_code(kind),
                *code,
                "{name} changed code: the committed table says {code}, the registry says {}. \
                 A wire code is a compatibility contract — a deployed client already knows \
                 the old value.",
                rpc_code(kind)
            );
        }
        // The other direction: a row naming something the registry no longer has is a
        // table that fell behind, which would let a deletion pass unnoticed.
        for (name, _) in &pinned {
            assert!(
                ErrorKind::ALL.iter().any(|&kind| wire_name(kind) == *name),
                "fixtures/d13-rpc-codes.tsv pins {name}, which is not a kind"
            );
        }
    }

    #[test]
    fn every_kind_survives_the_trip_out_and_back_as_the_same_typed_error() {
        // `Error::sample` is the walkable population D13 provides for exactly this — the
        // mapping, the renderer and the emitter all need one, and three hand lists would be
        // three lists that drift (schema's own doc comment says so).
        for &kind in ErrorKind::ALL {
            let error = Error::sample(kind);
            let object: ErrorObjectOwned = WireError(error.clone()).into();

            assert_eq!(object.code(), rpc_code(kind), "{kind:?}");
            // `message` is human, and it is `Error`'s own — not a second rendering.
            assert_eq!(object.message(), error.to_string(), "{kind:?}");
            assert!(
                !object.message().is_empty(),
                "{kind:?} crossed with no message"
            );

            let back = typed(&object).unwrap_or_else(|| panic!("{kind:?} did not decode back"));
            assert_eq!(back, error, "{kind:?} changed on the way through");
            // The property P4f's parity gate rests on: `wchc` renders the same string
            // `wch` does, because it renders the same value.
            assert_eq!(back.to_string(), error.to_string(), "{kind:?}");
        }
    }

    #[test]
    fn a_foreign_or_malformed_error_object_degrades_rather_than_becoming_a_camera_answer() {
        // Each arm is a different way of not being ours, and each would be a different lie
        // if `typed` guessed instead of refusing.

        // The transport's own failures, which share the band but not the block. Mistaking
        // one for a device answer is E3's conversion committed at the transport layer.
        let not_found =
            ErrorObjectOwned::owned(METHOD_NOT_FOUND_CODE, "Method not found", None::<()>);
        assert_eq!(typed(&not_found), None);
        let oversized =
            ErrorObjectOwned::owned(OVERSIZED_RESPONSE_CODE, "Response is too big", None::<()>);
        assert_eq!(typed(&oversized), None);

        // The same, *carrying data* — which is what jsonrpsee's invalid-params failure
        // actually looks like on this surface (measured: `{"code":-32602,"message":
        // "Invalid params","data":"No more params"}`). This arm is the one that would go
        // red if the kind-matches-code check were ever weakened to "the payload parses",
        // and it is why no range test is needed in front of it.
        let bad_params = ErrorObjectOwned::owned(
            INVALID_PARAMS_CODE,
            "Invalid params",
            Some(serde_json::json!("No more params")),
        );
        assert_eq!(typed(&bad_params), None);

        // One of our codes with nothing attached: a server that promised a typed error and
        // sent none.
        let empty =
            ErrorObjectOwned::owned(rpc_code(ErrorKind::Busy), "something happened", None::<()>);
        assert_eq!(typed(&empty), None);

        // One of our codes over a document that is not a `schema::Error`.
        let foreign = ErrorObjectOwned::owned(
            rpc_code(ErrorKind::Busy),
            "something happened",
            Some(serde_json::json!({ "whatever": 1 })),
        );
        assert_eq!(typed(&foreign), None);

        // Our code over *our* document, but not the matching one — the shape a proxy that
        // rewrote a code would produce. Believing the payload would report a busy camera as
        // a gone one, or the reverse.
        let mismatched = ErrorObjectOwned::owned(
            rpc_code(ErrorKind::DeviceGone),
            "mismatched",
            Some(Error::sample(ErrorKind::Busy)),
        );
        assert_eq!(typed(&mismatched), None);

        // A code far outside the band entirely — an application-level code from some other
        // service on the same socket — over one of our documents. Refused by the same
        // check as the arm above: `rpc_code(Busy)` is not 1001, and no kind maps to a code
        // outside [`D13_CODES`], so "outside the block" needs no test of its own.
        let application =
            ErrorObjectOwned::owned(1001, "not ours", Some(Error::sample(ErrorKind::Busy)));
        assert_eq!(typed(&application), None);

        // And the healthy twin, so every `None` above is a refusal of *that* object rather
        // than of everything: the real thing still decodes.
        let ours: ErrorObjectOwned = WireError(Error::sample(ErrorKind::Busy)).into();
        assert_eq!(typed(&ours), Some(Error::sample(ErrorKind::Busy)));
    }

    #[test]
    fn the_wire_error_adds_no_second_rendering_of_anything() {
        // D13: "the CLI renders the same variants; nobody stringly-matches". The newtype is
        // a transport adapter, so its `Display` has to be the error's own — a reworded one
        // here would be a second home for a sentence a human reads (design §2.10), and the
        // `wch`/`wchc` parity gate compares exactly these strings.
        for &kind in ErrorKind::ALL {
            let error = Error::sample(kind);
            assert_eq!(WireError(error.clone()).to_string(), error.to_string());
            assert_eq!(WireError::from(error.clone()).into_inner(), error);

            // And the same sentence once *down the chain*, which is the half a `Display`
            // assertion cannot see. std's contract is that `Display` must not include
            // what `source()` renders, so a `source()` answering `Some(&self.0)` would
            // make every chain printer in P4b's daemon log D13's one sentence twice —
            // measured as `cannot open /dev/video0: join the video group: cannot open
            // /dev/video0: join the video group`. The newtype is transparent: its source
            // is the *inner error's* source.
            let wire = WireError(error.clone());
            let mut chain: Vec<String> = vec![wire.to_string()];
            let mut link = std::error::Error::source(&wire);
            while let Some(current) = link {
                chain.push(current.to_string());
                link = current.source();
            }
            assert!(
                !chain[1..].contains(&error.to_string()),
                "{kind:?} renders twice down the chain: {chain:?}"
            );
        }
    }
}
