# Shared helpers for the webcam-handler gate predicates.
#
# docs/9's structural rule is that a gate written to close a defect is not itself tested
# against its own inverse, and the second arm is where it fails. `selftest.sh` proves the
# second arm by pointing a predicate at a *mutated copy* of the tree, so no predicate may
# assume it is looking at the checkout it lives in: every path resolves under
# `gate_root`, which the selftest overrides with $WCH_GATE_ROOT.
#
# The counters serve the other half of the same rule (AGENTS.md rule 3): a check that
# examined zero things is a check that cannot fail. Every predicate reports what it
# examined and how many, and calls `gate_require_nonzero` wherever a zero would be
# vacuous rather than informative.
#
# shellcheck shell=bash

# The tree under test. Absolute, no trailing slash.
gate_root() {
    if [[ -n "${WCH_GATE_ROOT:-}" ]]; then
        local root="${WCH_GATE_ROOT%/}"
        if [[ ! -d "$root" ]]; then
            printf 'gate: WCH_GATE_ROOT=%s is not a directory\n' "$root" >&2
            return 1
        fi
        printf '%s\n' "$root"
    else
        git rev-parse --show-toplevel
    fi
}

# --------------------------------------------------------------- where scratch goes
#
# **The ruling (owner, 2026-08-12):** "Given the repeated failures coming from tmpfs size
# limits, let's move all the temporary data generated by our tests under a subdirectory of
# `target/`, which is also marked as a cache / temporary directory." Note **N84** records
# what forced it, the recursion trap it opens, and what it deliberately does not move.
#
# What forced it was a **lifecycle** bug and not a size one, which is worth keeping straight
# because the fix for the two is different. `gate_scratch_tree` copies the checkout so a
# selftest arm can mutate a copy and run the real predicate against it; `selftest.sh` is the
# only caller that ever deleted the result, and every other caller — which is what running a
# single `cases/*.sh` arm by hand is, the ordinary move while a gate is being written — left
# it behind. Measured at the start of the P5d hardware session (**E15**): **76
# `/tmp/wch-tree.*` directories, 1 968 MB**, all timestamped eight hours earlier, in a 16 GB
# tmpfs. The symptom was not a red gate. It was the shell intermittently refusing to run
# anything, which is a very long way from the line that caused it.
#
# `target/` is the answer for three reasons and only the first is the ruling's:
#
#   1. cargo writes `target/CACHEDIR.TAG`, so every backup and indexing tool that reads that
#      file already knows this is regenerable — the directory is *declared* scratch rather
#      than merely used as it;
#   2. `/target/` is gitignored, so nothing written here can be committed by accident;
#   3. `gate_find` prunes `target`, so nothing written here becomes visible to a gate that
#      walks the tree — which is what keeps `no-frame-bytes-in-repo.sh` true about a session
#      tree full of sample photos, and what resolves the collision E15 recorded between that
#      gate and `.gitignore`'s late `/scratch/` entry.
#
# It trades RAM for disk, deliberately, and the trade was measured on the run that landed it:
# sampled every two seconds through `just ci`, this root peaked at **11 838 MB** while `/tmp`
# never moved off 33 MB. That peak is one arm — `counted-selections.sh`'s real-lister, which
# cold-builds the workspace inside a scratch copy (note **N71**) — against a tmpfs of 16 GB
# and a disk with 156 GB free. Which of the two numbers the peak is measured against is the
# whole of the ruling.

# The checkout these scripts live in, which is **not** `gate_root`.
#
# `gate_root` answers "the tree under test", and the selftest points that at a mutated copy.
# Scratch belongs to the real checkout instead: a predicate that wrote its scratch inside the
# copy it was reading would be reporting on its own leftovers, and `selftest.sh`'s "the
# checkout is as the arms found it" would be asserting it about the wrong tree. Resolved from
# this file's own location rather than from `$PWD` or from `git`, because several arms run
# with a scratch copy as their working directory and a source tarball has no `git` at all.
gate_checkout() {
    local here
    here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    printf '%s\n' "${here%/scripts/gates}"
}

# Where temporary data goes. Absolute, no trailing slash, created if it is not there.
#
# **One home for the choice.** Nineteen script files spelled `${TMPDIR:-/tmp}` before this
# existed, so "where does test scratch live" was a decision taken nineteen times and revisable
# in none of them.
#
# $WCH_GATE_SCRATCH still wins, and that is not a legacy seam kept out of politeness: it is
# how a caller puts scratch on a different filesystem — a bigger one, a faster one, a
# `tmpfs` on a machine that has the room — and it is what `selftest.sh` uses to give one
# run's arms a single directory it can reclaim between them.
#
# The directory is created here rather than by each caller because every caller wants it to
# exist and `mktemp` refuses a template whose directory does not; a failure to create it is
# reported by whoever asked, since a scratch root that cannot be made is a fact about the
# machine and not about the tree.
gate_scratch_root() {
    local root="${WCH_GATE_SCRATCH:-$(gate_checkout)/target/wch-scratch}"
    root="${root%/}"
    if ! mkdir -p "$root"; then
        printf 'gate: no scratch root at %s\n' "$root" >&2
        return 1
    fi
    printf '%s\n' "$root"
}

# Where a directory that is going to hold an `AF_UNIX` socket goes — and it is **not** under
# `target/`. Absolute, no trailing slash.
#
# `sockaddr_un::sun_path` is 108 bytes on Linux and the path inside it is NUL-terminated, so
# 107 is the bound (`schema::limits::MAX_UNIX_SOCKET_PATH_BYTES`, which the daemon checks
# before `bind` so that the refusal names the limit instead of arriving as an `EINVAL`).
# Measured on this checkout rather than guessed at, for the deepest socket any gate binds —
# `<root>/<gate scratch>/<runtime>/webcam-handler/wchd.sock`, with the selftest's own
# directory in the middle:
#
#     94 bytes   /tmp/…/wch-socket-activation.XXXXXXXX/journal-run/…/wchd.sock
#    146 bytes   <checkout>/target/wch-scratch/…/wch-socket-activation.XXXXXXXX/…/wchd.sock
#
# 146 against a bound of 107, and 37 of those bytes are `/home/pwnall/workspace/webcam-handler`
# — a number that is a property of **where somebody cloned this repository**. Moving these
# under `target/` would therefore not merely break three gates here; it would make their
# verdict a function of the checkout path, which is notes **N52**, **N66** and **N68** for the
# fourth time (a verdict that moves with the machine, wearing the word a real finding gets).
# A socket directory is also not what filled the tmpfs: it holds a socket, a fifo and an empty
# state tree, and it is kilobytes. So the bulk moves and the socket root stays short, both
# decided here, once.
#
# $WCH_GATE_SCRATCH deliberately does **not** win here. Its job is "put the bulk on another
# filesystem", and honouring it for a socket would import a caller's path depth into a kernel
# constant. What reclaims these after a `kill -9` is `gate_scratch_sweep`, which sweeps this
# root as well.
gate_socket_scratch_root() {
    # wch-scratch-exempt: this function IS the socket root; see the measurement above
    local root="${TMPDIR:-/tmp}"
    printf '%s\n' "${root%/}"
}

# Reclaim scratch that no run is coming back for, from both roots. Prints what it did.
#
#   $1  the age in minutes below which an entry is presumed live (default 1440, a day)
#
# **A killed run cannot clean up after itself, which is exactly how 76 copies accumulated**,
# so "delete it at the end" cannot be the whole answer: a `trap` does not run after `kill -9`,
# and neither does `selftest.sh`'s per-arm reclaim. The only process that can reclaim an
# abandoned directory is a later one, so this is written to be run by the next run
# (`selftest.sh` calls it before it starts) and by a person (`just scratch-sweep`, which
# passes 0 and takes everything).
#
# Only entries named `wch*` are touched, which is every name any of these scripts and
# `engine::paths::scratch_dir` produce. That is a deliberate floor rather than a filter for
# tidiness: `target/wch-scratch/` is also where the R1-web rung leaves the traces and
# screenshots a person opens *after* a failing run, and where a hardware session parks its
# transcripts, and a sweep that took those would be a sweep nobody dares run.
#
# What it does not cover is named in note N84: a caller's own $WCH_GATE_SCRATCH somewhere
# else, cargo-mutants' `cargo-mutants-*` build trees, and anything under either root that a
# person named something other than `wch…`.
gate_scratch_sweep() {
    local age="${1:-1440}" root swept=0 entry plural='ies'
    for root in "$(gate_scratch_root)" "$(gate_socket_scratch_root)"; do
        [[ -d "$root" ]] || continue
        while IFS= read -r -d '' entry; do
            if rm -rf "$entry"; then
                swept=$((swept + 1))
            fi
        done < <(find "$root" -mindepth 1 -maxdepth 1 -name 'wch*' -mmin "+$age" -print0 2>/dev/null)
    done
    if ((swept == 1)); then
        plural='y'
    fi
    printf 'scratch-sweep: reclaimed %s abandoned entr%s older than %s minute(s), from %s and %s\n' \
        "$swept" "$plural" "$age" "$(gate_scratch_root)" "$(gate_socket_scratch_root)"
}

# --------------------------------------------------------------- the third outcome
#
# A check has three answers, not two: it can pass, it can find something, and it can be
# **unable to answer at all**. The third one had no spelling in this suite until note N68,
# and the cost of that is three entries long: N52 (the mutation floor's verdict moved with
# `nproc`), N66 (it moved with the free space on `/tmp`) and N68 (it moved when an agent
# edited a file the run was still reading). All three reported the same word — FAIL — as a
# surviving mutant gets, and N60 records what that costs: "a gate that cries wolf does not
# get believed, it gets re-run at `-j1` until it agrees, and the run after that is the one
# where a real survivor is waved through".
#
# So a run that could not produce a verdict exits **75**, and that number is not invented:
# it is `EX_TEMPFAIL` from `sysexits.h` — "temporary failure; the user is invited to retry"
# — which is exactly the claim being made. The alternatives were considered and rejected:
#
#   - **0** is wrong because the criterion is *not proven*. An unprovable criterion that
#     reads as green is the "skip that reads as pass" AGENTS.md rule 3 forbids, wearing an
#     exit code.
#   - **1** is what a finding uses, and telling the two apart is the whole point.
#   - **2** is already taken by `phase.sh`'s usage error, and by cargo-mutants' "some
#     mutants survived" — a number that means two things in one pipeline means neither.
#
# It is non-zero, so nothing that composes these scripts can accidentally treat it as
# success; it is *distinct*, so anything that wants to can tell the machine's shortfall
# from the code's. `phase.sh` does; `scripts/mutants.sh` produces it.
GATE_NO_VERDICT=75

# --------------------------------------------------------------- reporting state

GATE_NAME="${GATE_NAME:-$(basename "${0}" .sh)}"
GATE_FAILURES=0
GATE_NO_VERDICTS=0
GATE_TOTAL=0
declare -a GATE_CHECKS=()
declare -a GATE_SKIPS=()

# Record that `count` things of a kind were examined. Printed by `gate_finish`, so a
# reader of CI output can see the population each claim rests on.
gate_checked() {
    local count="$1"
    shift
    GATE_CHECKS+=("$count $*")
    GATE_TOTAL=$((GATE_TOTAL + count))
}

# A skip that is named and counted, never silence (AGENTS.md rule 3).
gate_skip() {
    local count="$1"
    shift
    GATE_SKIPS+=("$count $*")
    printf '  SKIP  %s: %s (%s)\n' "$GATE_NAME" "$*" "$count"
}

# An informational line. Reasoning a reader needs; not a verdict.
gate_note() {
    printf '  note  %s\n' "$*"
}

gate_fail() {
    GATE_FAILURES=$((GATE_FAILURES + 1))
    printf '  FAIL  %s: %s\n' "$GATE_NAME" "$*" >&2
}

# Something this run could not answer — a resource it did not have, an interruption, an
# input that moved underneath it. Not a finding, and never a pass: see `GATE_NO_VERDICT`
# above. The word is spelled out rather than abbreviated because the reader this exists
# for is skimming a CI log for the string "FAIL".
gate_no_verdict() {
    GATE_NO_VERDICTS=$((GATE_NO_VERDICTS + 1))
    printf '  NO VERDICT  %s: %s\n' "$GATE_NAME" "$*" >&2
}

# A population of zero means the predicate examined nothing and therefore proved
# nothing. Callers use this wherever an empty population is a defect rather than a
# legitimate not-yet-landed state; where it is legitimate, they call `gate_skip`.
gate_require_nonzero() {
    local count="$1"
    shift
    if ((count == 0)); then
        gate_fail "examined zero $* — a check that examines nothing cannot go red"
    fi
}

gate_finish() {
    local line
    if ((${#GATE_CHECKS[@]} > 0)); then
        for line in "${GATE_CHECKS[@]}"; do
            printf '  ok    %s: checked %s\n' "$GATE_NAME" "$line"
        done
    fi
    # A finding outranks a no-verdict, and the ordering is deliberate: if this run both
    # found something and failed to answer something else, the thing it *found* is the
    # thing to act on, and "could not answer" would be the softer of the two words to end
    # on. The unanswered part is still named on the line above, so it is not lost.
    if ((GATE_FAILURES > 0)); then
        if ((GATE_NO_VERDICTS > 0)); then
            printf 'NO VERDICT %s — and %s check(s) could not produce a verdict at all\n' \
                "$GATE_NAME" "$GATE_NO_VERDICTS" >&2
        fi
        printf 'FAIL %s — %s violation(s) over %s examined items\n' \
            "$GATE_NAME" "$GATE_FAILURES" "$GATE_TOTAL" >&2
        exit 1
    fi
    if ((GATE_NO_VERDICTS > 0)); then
        printf 'NO VERDICT %s — %s check(s) could not answer over %s examined items; nothing here is a finding about the code, and nothing here is a pass either\n' \
            "$GATE_NAME" "$GATE_NO_VERDICTS" "$GATE_TOTAL" >&2
        exit "$GATE_NO_VERDICT"
    fi
    printf 'PASS %s — %s items examined, %s named skip(s)\n' \
        "$GATE_NAME" "$GATE_TOTAL" "${#GATE_SKIPS[@]}"
    exit 0
}

# --------------------------------------------------------------- tree traversal
#
# Populations are derived by walking the tree, never transcribed (docs/9's second
# structural rule). `target/`, `.git/`, `vendor/` and `node_modules/` are excluded
# everywhere: the first two are not source, `vendor/v4l2-webcam-skill/` is a read-only
# upstream reference this project does not own, and `node_modules/` is the R1-web rung's
# installed tooling (design §3.1) — gitignored, restored by `just rung-web-install` from a
# committed lockfile, and no more ours than `target/` is.
#
# **The fourth name was added at P5d and it is worth saying what it cost**, because a
# privacy gate that quietly stops looking somewhere is the class this suite exists for:
# `no-frame-bytes-in-repo.sh` sniffs every file this walk finds, and Playwright ships two
# `appIcon.png`s. Neither can reach the repository — the directory is gitignored and the
# gate's own sentence is about what is *committed* — but the walk had no way to say so, and
# an installed dependency tree is not a place a camera frame can appear. What is *not* done
# here, deliberately, is switching the walk to `git ls-files`: a frame written into the tree
# and not yet committed is precisely what that gate is for, and asking git would stop seeing
# it.

# Print, NUL-separated, every file under $1 (default: the whole tree) matching the
# remaining `find` predicates.
gate_find() {
    local dir="$1"
    shift
    [[ -d "$dir" ]] || return 0
    find "$dir" \
        \( -name target -o -name .git -o -name vendor -o -name node_modules \) -prune -o \
        -type f "$@" -print0
}

# Every Rust source file in the tree under test.
gate_rust_files() {
    gate_find "$(gate_root)" -name '*.rs'
}

# --------------------------------------------------------------- product code vs test code
#
# **Seven predicates** make claims about what a *file* says and must not count what its own
# tests say, and the count is written down because a change here changes all seven:
# `token-comparison-has-one-home.sh` (who may read the token's secret and who may render its
# URL), `web-routes-are-gated.sh` (what may register a route), `privileged-helper.sh` (what may
# hand this binary's capabilities to a caller-named program), `avi-reparse-is-independent.sh`
# (what the reparser may import), `oracle-rung-accounting.sh` (what the oracle runner may say),
# `claims-come-back-with-their-values.sh` (what a claim may be built from) and
# `facade-is-the-composition.sh` (what the direct CLI's executor may name in the engine, and
# which engine modules the facade composes on its behalf — it is the only caller that reads
# *two* files through this classifier, because its population and its subject are different
# files). A test that builds a router of its own, holds a secret to construct a near miss with,
# drives the engine directly, or writes the very spelling a predicate refuses in order to prove
# the refusal, is not the defect any of them is about — and a gate that refused those is a gate
# somebody turns off.
#
# This header used to say "two predicates", and it said so through four of the six arriving.
# That is not a typo worth a line of its own: a shared classifier whose header names a subset of
# its callers is one somebody edits while reasoning about the subset, which is exactly how the
# `tests/` rule below landed with two callers considered and six affected (note **N185**).
#
# **The rule is one sentence, and it is the shape every module in this workspace writes: test
# code is everything from a file's one `#[cfg(test)]` marker to the end of it.** A file this
# cannot classify — two markers, or a marker that opens something other than a `mod` — is a
# **failure and not a pass** in every caller, because a file whose boundary has no answer is a
# file where the confinement has none either; that is `unsafe-scope.sh`'s price for a count it
# cannot read, charged for a boundary. The residual is the other end: product code placed
# *after* a trailing test module would not be seen. Nothing in this workspace is written that
# way, and both predicates' `cases/` seed the shapes that are.
#
# One home rather than two copies, for `gate_tree_state`'s reason a few paragraphs down: the
# second copy is the one that stops agreeing about what a test region is, and the two callers
# would then disagree about which half of a file they were reading.

# The line where $1's test region begins: 0 for a file with no test module, and -1 for a file
# whose test region this cannot identify.
#
# **A file in a `tests/` directory is test code from its first line**, and that is cargo's rule
# rather than a convention this file invented: `crates/<pkg>/tests/*.rs` is compiled only by
# `cargo test`, so there is no product code in one and a `#[cfg(test)]` marker would be
# redundant — which is why none of them carries one, and why the marker rule alone would read
# every line of an integration suite as shipped code. All seven callers want the same answer about
# them (a suite that holds the token to build a near miss with, or builds a router of its own,
# is not the defect any of those predicates is about), so the rule lives here beside the other
# half of the classification rather than in one of them. The residual is the mirror image and is
# harmless: a `src/tests/` module directory would be read as test code too, which is what it
# would be.
#
# **Matched against the path relative to `gate_root`, and that is the whole of the rule's
# correctness** (note **N185**). Callers pass absolute paths — `"$file"` off `gate_rust_files`,
# `"$root/$module"` — so matching `$1` itself asks a question about *where somebody cloned this
# repository*: a checkout under `~/tests/`, or a scratch copy a harness put beside a `tests`
# directory, classifies **every** file in the tree as test code from line 1, `gate_product_lines`
# answers zero bytes, and five of the seven callers fail loudly while two go vacuously green
# (`privileged-helper.sh`'s caller-named-program claim and `avi-reparse-is-independent.sh`'s
# import claim both keep a non-zero count while reading nothing). That is a verdict that is a
# function of the checkout path, which is notes **N52**, **N66** and **N68** for the fifth time,
# introduced into the one classifier all seven share. A root that cannot be resolved leaves the
# path as it is, which is the marker rule alone — the answer this helper gave before the
# `tests/` rule existed, and never a silent reclassification of the whole tree.
gate_test_region_start() {
    local root rel="$1"
    if root="$(gate_root 2>/dev/null)"; then
        rel="${1#"$root"/}"
    fi
    if [[ "$rel" == */tests/* || "$rel" == tests/* ]]; then
        printf '1\n'
        return 0
    fi
    awk '
        /^[[:space:]]*#\[cfg\(test\)\]/ {
            markers++
            if (!first) { first = NR }
            expect_mod = NR + 1
        }
        NR == expect_mod && $0 !~ /^[[:space:]]*mod[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\{/ {
            unreadable = 1
        }
        END {
            if (markers == 0) { print 0 }
            else if (markers > 1 || unreadable) { print -1 }
            else { print first }
        }
    ' "$1"
}

# The product half of $1 — everything above the test region that starts at line $2 — with line
# comments stripped.
#
# **Prose does not count**, in every caller and for the same reason: what defends each claim is
# the argument written beside the code, those arguments name the very spellings the predicates
# match on, and a gate that turned writing about a rule into a violation would push the
# reasoning out of the modules that need it. Block comments and string literals are not
# stripped, for `unsafe-scope.sh`'s reason — the workspace writes `//` comments, and a rule that
# fits in one sentence beats one that needs a Rust parser.
gate_product_lines() {
    local file="$1" start="$2" last='$'
    if ((start == 1)); then
        return 0
    fi
    if ((start > 1)); then
        last=$((start - 1))
    fi
    sed -n "1,${last}p" "$file" | sed 's://.*::'
}

# --------------------------------------------------------------- reading Rust source text
#
# **Two predicates read "which paths does this file name" and both were written narrow.** Note
# **N269** measured the first: a `{` after the colons ended the match attempt, so a grouped
# import yielded no path and the gate passed with a summary byte-identical to the unseeded
# tree's. Note **N271** measured the second, written in the same commit as the repair for the
# first and carrying a fresh copy of the same hole. `rust-imports.awk` beside this file is the
# one home for the joining and flattening both of them need; this is where a predicate finds it,
# so a caller writes a path to it in exactly one place.
gate_rust_imports_awk() {
    printf '%s/rust-imports.awk\n' "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
}

# Every module `pub mod`-declared by the crate root $1, printed one per line.
#
# **Both spellings of a declaration, because a ban names the class** (note **N249**): a file
# module ends the line with `;` and an inline one opens a block with `{`, and a walk that read
# only the first would let `pub mod telemetry { … }` join neither column of D18's stability
# table and neither side of `facade-is-the-composition.sh`'s policy check. The engine declares
# file modules exclusively today, which is exactly why nothing here had ever caught it.
gate_pub_mods() {
    sed 's://.*::' "$1" |
        grep -oE '^pub mod [a-z_][a-z0-9_]*[[:space:]]*[;{]' |
        sed 's/^pub mod //; s/[[:space:]]*[;{]$//'
}

# --------------------------------------------------------------- cargo metadata
#
# `cargo metadata` is the authority on the dependency graph: manifests lie by omission
# (a feature enabled by a transitive dependency is invisible in the manifest that
# forbids it). $WCH_GATE_METADATA lets the selftest feed a doctored graph to the failing
# arm — the passing arm always resolves the real tree, because a predicate whose only
# input is injectable proves nothing about the repository.
gate_metadata() {
    if [[ -n "${WCH_GATE_METADATA:-}" ]]; then
        cat "$WCH_GATE_METADATA"
    else
        cargo metadata --locked --offline --format-version 1 \
            --manifest-path "$(gate_root)/Cargo.toml"
    fi
}

# --------------------------------------------------------------- the population
#
# The predicate population is the directory listing minus the harness. Neither
# `run-all.sh` nor `selftest.sh` keeps a list, so a predicate added to the directory is
# run and self-tested without anybody remembering to register it — which is the failure
# docs/9's derived-population rule exists to prevent.
#
# The harness names *are* a list, and that is the bootstrap limit docs/9 records: the
# selftest cannot test the harness. It is closed as far as it can be — each name is
# asserted to exist, so a rename fails loudly instead of quietly promoting a harness file
# into the population it drives.
GATE_HARNESS_FILES=(lib.sh run-all.sh selftest.sh phase.sh)

gate_predicates() {
    local dir file base harness is_harness
    dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    for harness in "${GATE_HARNESS_FILES[@]}"; do
        if [[ ! -f "$dir/$harness" ]]; then
            printf 'gate: harness file %s is missing from %s\n' "$harness" "$dir" >&2
            return 1
        fi
    done
    for file in "$dir"/*.sh; do
        base="$(basename "$file")"
        is_harness=0
        for harness in "${GATE_HARNESS_FILES[@]}"; do
            if [[ "$base" == "$harness" ]]; then
                is_harness=1
            fi
        done
        if ((is_harness == 0)); then
            printf '%s\n' "$file"
        fi
    done
}

# Write the real workspace's `cargo metadata` to a scratch file and echo the path. The
# failing arms doctor a copy of the real graph rather than inventing one, so a seeded
# violation differs from the shipped tree in exactly the one way the case describes.
#
# **It never echoes an empty path, and that is not defensiveness — it is a measured
# defect.** Seven case files spell their seeded copy `"$md.seeded"`, so a `$md` that came
# back empty makes that `.seeded`, resolved against the *checkout* — which is precisely
# what the paragraph below `gate_scratch_tree` forbids ("predicates have no side effects
# on the tree, and neither may the cases that exercise them"). It happened: a full scratch
# filesystem made `mktemp` fail, and a zero-byte `.seeded` appeared at the repository root.
# `run_case` deliberately runs without `set -e`, so nothing downstream was going to stop
# it, and inside a `fail_case_` a seeding failure is indistinguishable from the predicate
# going red — which is the one confusion this harness must not have. So the fallback is a
# path that is still *outside the walk*: it is under the scratch root, which since the
# 2026-08-12 ruling is `target/`, which `gate_find` prunes — so a caller that ignores this
# failure writes somewhere no gate can see, and `selftest.sh` catches the class rather than
# this instance.
gate_metadata_snapshot() {
    local out scratch
    scratch="$(gate_scratch_root)"
    if ! out="$(mktemp "$scratch/wch-metadata.XXXXXXXX")" || [[ -z "$out" ]]; then
        printf 'gate: no scratch file for a metadata snapshot in %s (full filesystem?)\n' \
            "$scratch" >&2
        out="$scratch/wch-metadata-unavailable.$$"
    fi
    (
        unset WCH_GATE_METADATA
        gate_metadata >"$out"
    )
    printf '%s\n' "$out"
}

# --------------------------------------------------------------- the tree, watched
#
# Two jobs here read the working tree for a long time and must not report a conclusion
# about a tree that changed while they were reading it:
#
#   - `selftest.sh` runs every case arm and then checks that no arm touched the checkout
#     (its `tree_before` block, and the paragraph there says why it is *recorded and
#     compared* rather than asserted clean — a developer's dirty tree is not a finding);
#   - `scripts/mutants.sh` reads the tree for the better part of an hour, one mutant at a
#     time, and note **N68** records the run whose input moved underneath it: a `just
#     gate-g4` started at 08:14 was still running at 09:19 when three files inside its
#     scope were edited, and it reported three acceptances as lies.
#
# One law, one home. The alternative was the same eight lines in both scripts, which is
# what AGENTS.md's "a second copy or a bypass is a defect" is about — and the copies would
# have drifted immediately, because `mutants.sh` needs the commit as well as the dirty
# state and `selftest.sh` did not have it.
#
# `scripts/mutants.sh` sources this file for exactly these three functions and
# `GATE_NO_VERDICT`. It is not a gate predicate and it keeps its own `mutants:` reporting
# vocabulary; sourcing a library is not adopting its output format.

# Is $1 a tree whose state git can report? A source tarball, or a checkout whose git is
# broken or absent, is not — and that is a missing tool rather than a violation, so every
# caller answers it with a named, counted skip.
gate_tree_watchable() {
    git -C "$1" rev-parse --git-dir >/dev/null 2>&1
}

# The state of the tree at $1, as one string: the commit, then `git status --porcelain`.
#
# Both halves are load-bearing and neither implies the other. `--porcelain` covers
# untracked files, which is the shape `selftest.sh`'s defect took (a stray `.seeded` at the
# repository root) and the shape an agent's new file takes. The commit covers the case
# porcelain cannot see at all: a `git checkout` or a rebase that moves HEAD and leaves the
# tree clean at both ends, which is the same "the input moved" event wearing a different
# hat.
gate_tree_state() {
    printf 'HEAD %s\n' "$(git -C "$1" rev-parse HEAD 2>/dev/null || printf '<none>')"
    git -C "$1" status --porcelain 2>/dev/null
}

# The lines by which two `gate_tree_state` recordings differ, `<` for the older and `>` for
# the newer. Callers print this verbatim: a reader's first question is always *which
# files*, and the answer is right there in the porcelain lines.
gate_tree_changes() {
    diff <(printf '%s\n' "$1") <(printf '%s\n' "$2") | grep -E '^[<>]' || true
}

# --------------------------------------------------------------- what a failing arm asserts
#
# `selftest.sh`'s verdict for a `fail_case_` is one number: the predicate's exit status. That is
# the right verdict and it is not enough on its own, because a seeded violation is often red
# under more than one branch — dropping an emission makes the old name an orphan *and* makes the
# committed copy stale; deleting a module makes the confinement vacuous *and* removes the
# anchor. An arm reading only the status cannot tell which branch fired, so a branch can rot to
# unreachable while its arm stays comfortably non-zero, which is note **N10**'s family: a gate
# green while checking less than it claims.
#
# So an arm names the sentence it is claiming. **Green is how this harness says "look at me"** —
# a predicate that stayed green, or that went red about something else, makes the arm exit 0,
# which `selftest.sh` reports as a problem rather than passing over.
#
# One home rather than three: this was written for `cases/schema-artifacts-current.cases.sh`
# (note **N31**), copied verbatim into `cases/cli-parity.cases.sh`, and the P5 review's third
# caller is what made the copies a decision rather than an accident. The two that existed were
# still byte-identical only because nobody had yet edited either, which is the state every
# second copy is in right up until it is not.
#
# **It records that it was called**, in the file below, because N31's *Retires when* is the
# harness requiring this rather than a case file remembering it (note **N243**). The record is
# written on entry and not on success: what `selftest.sh` asks is whether the arm named a
# sentence at all, and an arm whose named sentence did not fire has already failed loudly two
# lines down. It is a fact about the arm rather than about the tree, which is why it is recorded
# where the dead-seed report is and read the same way.
#
#   $1  a fixed string the predicate's output must contain while failing
#   $2… the command to run
gate_red_because() {
    local pattern="$1"
    shift
    printf '%s\n' "$pattern" >>"$(gate_claim_report)" || true
    local output status=0
    output="$("$@" 2>&1)" || status=$?
    if ((status == 0)); then
        printf 'the predicate stayed green; it was expected to fail with: %s\n%s\n' \
            "$pattern" "$output" >&2
        return 0
    fi
    if ! grep -Fq -- "$pattern" <<<"$output"; then
        printf 'the predicate went red, but not because of: %s\n%s\n' "$pattern" "$output" >&2
        return 0
    fi
    return "$status"
}

# Where an arm records the sentence it claimed, so `selftest.sh` can require one.
#
# Same home and same lifetime as `gate_seed_report`: under the run's scratch directory, which the
# harness empties between arms, so what is there belongs to the arm that just ran. Run by hand it
# lands under `target/wch-scratch/` where `gate_scratch_sweep` will take it.
gate_claim_report() {
    printf '%s/wch-arm-claim.report\n' "$(gate_scratch_root)"
}

# Prove the recording both ways, before the harness decides anything on it.
#
# `selftest.sh` runs this beside `gate_seed_selfcheck` and for the same bootstrap reason (docs/9:
# the selftest cannot test the harness). The direction that matters is the second one: a recorder
# that answered "named" to everything would let every arm in `cases/` drop its claim and go on
# reporting `ok`, which is the defect this whole mechanism exists to close — the register in
# `named-arm-register.txt` would then be a list of files nothing was checking.
gate_claim_selfcheck() {
    local report status=0 red
    report="$(gate_claim_report)"
    rm -f "$report"
    # A predicate-shaped command: red, and saying one sentence while it is.
    red=(bash -c 'printf "the seeded violation is here\n" >&2; exit 3')

    # `|| true` on both drives: these commands are *meant* to be red, and a caller with `set -e`
    # would otherwise take their exit status as its own.
    "${red[@]}" >/dev/null 2>&1 || true
    if [[ -e "$report" ]]; then
        printf 'gate_red_because: an arm that named nothing was recorded as having named something\n' >&2
        status=1
    fi

    gate_red_because 'the seeded violation is here' "${red[@]}" >/dev/null 2>&1 || true
    if [[ ! -s "$report" ]]; then
        printf 'gate_red_because: an arm that named its sentence left nothing for the harness to read\n' >&2
        status=1
    fi

    rm -f "$report"
    return "$status"
}

# --------------------------------------------------------------- scratch copies

# Copy the tree under test somewhere writable and echo the path. Used by the selftest's
# failing arms to seed a violation without touching the checkout — predicates have no
# side effects on the tree, and neither may the cases that exercise them.
#
# ## `--exclude=target` changed jobs on 2026-08-12 and it is now load-bearing
#
# It used to be an optimisation. The worktree minus `.git` and `target` is 46 MB and
# `target/` alone is **233 GB**, so dropping the exclusion bought a copy nobody could
# afford — slow and wasteful, and nothing worse than that, because the destination was in
# `/tmp` and could not be part of the source.
#
# Since the ruling above the destination is **inside the source tree**, and the same word now
# stops a copy from containing itself. Both halves of that were measured on a synthetic tree
# rather than reasoned about, because the reasoning has an obvious answer that turns out to be
# only half right:
#
#   - with `--exclude=target` removed and the derived exclusion below still in place, the copy
#     comes out holding `target/` and **no** nesting — which on this tree is 233 GB per arm,
#     roughly two hundred times per selftest run: ruinous, and bounded;
#   - with both removed, the copy came out holding one nested `…/target/wch-scratch/wch-tree.…`
#     of itself. How deep it goes is a race between `tar`'s reading of a directory and the
#     extraction writing into it, so "it recurses forever" is an over-claim and "it recurses"
#     is not.
#
# Two things hold it:
#
#   - **the second exclusion below**, derived from where the copy is actually going rather
#     than written down, so it survives somebody editing the line above it; and
#   - **`scratch-has-one-home.sh`**, which asserts both that a real copy contains no `target`
#     and no nested scratch root, and that the copier in the tree under test still names the
#     exclusion. The static half exists because the honest dynamic test — run the shipped
#     copier over the shipped tree with the exclusion gone — copies 233 GB into the tree, and
#     a gate does not get to perform the defect it is checking for.
gate_scratch_tree() {
    local src dest scratch_root
    local excludes=(--exclude=.git --exclude=target)
    src="$(gate_root)"
    scratch_root="$(gate_scratch_root)"
    dest="$(mktemp -d "$scratch_root/wch-tree.XXXXXXXX")"
    # Belt to the exclusion's braces, and the half that is *derived*: name the place the copy
    # is going, so a copy cannot contain it. `tar -C "$src" -cf - .` emits members as `./…`,
    # so the pattern is the root's path relative to the source with that prefix on it.
    # Unconditional on purpose — when the root is somewhere else entirely the strip leaves an
    # absolute path, the pattern comes out as `.//…`, and nothing in the archive is named that
    # — because an `if` around it is a line whose body somebody can delete and leave valid
    # shell behind.
    excludes+=(--exclude="./${scratch_root#"$src"/}")
    tar -C "$src" -cf - "${excludes[@]}" . | tar -C "$dest" -xf -
    printf '%s\n' "$dest"
}

# --------------------------------------------------------------- seeding a violation
#
# **A seed that stops applying is the one arm failure this harness could not see** (note
# **N186**). Nearly every case in `cases/` seeds by quoting a line of the tree into a `sed`
# expression, so an arm's subject is produced by a substitution against a spelling somebody else
# is free to change. When the spelling moves the substitution matches nothing, the copy is
# pristine, the predicate is green — and what the harness says next depends on which kind of arm
# it was:
#
#   - a `fail_case_` exits 0, and `selftest.sh` reports *"the seeded violation did not turn the
#     predicate red"* — loud, and about the wrong subject: the sentence names the predicate when
#     the fact is about the seed, which is note **N60**'s cost in its smallest form (a verdict
#     somebody re-runs and then waves through);
#   - a `pass_case_` exits 0, and the harness prints **`ok`**. The arm's entire subject was never
#     produced, the predicate was run against an unmodified tree, and nothing said so. That is a
#     skip that reads as a pass, in the file whose job is to prove things can fail.
#
# Note N184 recorded the class and argued no general fix was available, on the ground that a
# seed is only checkable against the line it quotes. **That objection is answered by asking a
# smaller question.** This does not ask whether the seed meant what its author meant; it asks
# whether it *edited anything at all* — a fact about bytes, mechanical, and true of all 66 seeds
# in this directory. Every one of them exists to change the tree, so "changed nothing" is a
# broken arm whatever the arm was for.
#
#   $1   the `sed` expression, exactly as `sed -i` takes it
#   $2…  the files to apply it to; **at least one of them must change**
#
# The population is the whole call rather than each file, because two callers legitimately seed
# a list where only some members match — `corpus-floor.cases.sh` strips three profile names from
# every file that mentions any of them, and `lint-posture.cases.sh` deletes one attribute line
# from three crate roots. What is broken is a seed that reached *nothing*, and that is the
# question this asks.
#
# **It reports where the arm's exit status cannot.** A dead seed is written to a file
# `selftest.sh` reads after every arm and before it decides anything, so the verdict names the
# seed in a `pass_case_` and a `fail_case_` alike. Returning non-zero as well is honest and is
# not the mechanism: the arms that would have to check it are precisely the arms that do not.
gate_seed() {
    local expression="$1"
    shift
    if (($# == 0)); then
        gate_seed_died "no file was named for \`sed -i $expression\`"
        return 1
    fi

    local file before after changed=0
    for file in "$@"; do
        if [[ ! -f "$file" ]]; then
            gate_seed_died "\`sed -i $expression\` was given $file, which is not a file"
            return 1
        fi
        # `cksum` off standard input, so the digest is of the bytes and carries no file name to
        # differ on. Content and not `mtime`: a `sed -i` rewrites the file whether or not the
        # expression matched, so the timestamp always moves and would answer "changed" to
        # everything.
        before="$(cksum <"$file")"
        if ! sed -i "$expression" "$file"; then
            gate_seed_died "\`sed -i $expression\` failed on $file"
            return 1
        fi
        after="$(cksum <"$file")"
        [[ "$before" == "$after" ]] || changed=$((changed + 1))
    done

    if ((changed == 0)); then
        gate_seed_died "\`sed -i $expression\` changed nothing in: $*"
        return 1
    fi
    return 0
}

# Where a dead seed is reported, so a verdict can name it whatever the arm's exit status was.
#
# Under `selftest.sh` this is the run's own scratch directory, wiped between arms, so what is
# there belongs to the arm that just ran. Run by hand — the ordinary move while a gate is being
# written — it lands under `target/wch-scratch/` where `gate_scratch_sweep` will take it, and
# the stderr line below is what the person sees.
gate_seed_report() {
    printf '%s/wch-dead-seed.report\n' "$(gate_scratch_root)"
}

# Say a seed did not apply, on standard error and in the report `selftest.sh` reads.
gate_seed_died() {
    printf 'gate: the seed did not apply — %s\n' "$1" >&2
    printf '%s\n' "$1" >>"$(gate_seed_report)" || true
}

# Prove `gate_seed` both ways, on a file of its own, before any arm relies on it.
#
# `selftest.sh` runs this first. The bootstrap limit docs/9 records is that the selftest cannot
# test the harness, and this is that limit closed as far as it goes: a guard that had silently
# stopped guarding would leave every `pass_case_` in this directory able to run against a
# pristine tree and report `ok`, which is the exact defect the helper exists to close. Two
# directions, because a helper that answered "dead" to everything would also pass a check that
# only drove the failing one.
gate_seed_selfcheck() {
    local dir file report status=0
    dir="$(mktemp -d "$(gate_scratch_root)/wch-seed-selfcheck.XXXXXXXX")"
    file="$dir/subject.txt"
    printf 'the line a seed quotes\n' >"$file"
    report="$(gate_seed_report)"
    rm -f "$report"

    if ! gate_seed 's/quotes/moved/' "$file"; then
        printf 'gate_seed: a seed that applies was reported dead\n' >&2
        status=1
    fi
    if ! grep -Fq 'moved' "$file"; then
        printf 'gate_seed: the expression was not applied to the file\n' >&2
        status=1
    fi
    if [[ -e "$report" ]]; then
        printf 'gate_seed: a seed that applied was written to the report\n' >&2
        status=1
    fi

    if gate_seed 's/a-spelling-this-file-does-not-have/x/' "$file" 2>/dev/null; then
        printf 'gate_seed: a seed that changed nothing was reported alive\n' >&2
        status=1
    fi
    if [[ ! -s "$report" ]]; then
        printf 'gate_seed: a dead seed left nothing for the harness to read\n' >&2
        status=1
    fi

    rm -rf "$dir"
    rm -f "$report"
    return "$status"
}
