#!/usr/bin/env bash
#
# The mutation floor tells its three outcomes apart, and the phase gate keeps them apart —
# note **N68**, and the class N52 and N66 opened before it.
#
# ## Why this predicate exists at all
#
# `scripts/mutants.sh` is a `g4` criterion **command**, not a predicate under
# `scripts/gates/`. So `selftest.sh` never reached it, it had no case file, and nothing
# proved any of its verdicts could be wrong. That is not an oversight of one file: it is
# why the same defect survived three encounters. N52 found the floor's verdict moving with
# `nproc` (time), N66 found it moving with the free space on `/tmp` (space), and N68 found
# it moving because an agent edited three files while the run was still reading them. Each
# time the floor said **FAIL**, which is the word a surviving unaccepted mutant gets, and
# each time the honest answer was "this run could not tell you anything".
#
# The three answers the floor must keep apart:
#
#   - **green** (exit 0) — it ran, and the acceptance register is clean in both directions;
#   - **a finding** (exit 1) — a survivor with no acceptance, or an acceptance that stopped
#     surviving. A statement about the code and the register;
#   - **no verdict** (exit $GATE_NO_VERDICT) — a resource shortfall, an interruption, a
#     baseline that would not build, a result set with rows missing, or an input that moved
#     underneath the run. Non-zero, because the criterion is not proven; distinct, because
#     it is not a finding, and `lib.sh` argues the number.
#
# ## What it drives, and the seam — because a real run is forty minutes
#
# A real floor run rebuilds the workspace once per mutant. Nothing in `just ci` can afford
# it, and a predicate that could only be proved by a forty-minute job is a predicate nobody
# would prove. But **the part that was wrong is not the running, it is the classifying**,
# and cargo-mutants writes its result as a directory of text files — `caught.txt`,
# `missed.txt`, `timeout.txt`, `unviable.txt`, one mutant per line, beside `outcomes.json`.
#
# So a recorded run is a fixture, and `scripts/mutants.sh` takes one: $WCH_MUTANTS_CLASSIFY
# points it at such a directory and it classifies it and exits, building nothing. That is
# the documented seam this predicate drives, and it is a **mode of the shipped script, not a
# reimplementation of it** — rubric rule 6's requirement that at least one arm runs the real
# thing (note N10). The mutants in the fixtures were generated by a real run once; what runs
# here is the real verdict logic, the real register parsing, the real multiset comparison and
# the real exit codes.
#
# The fixtures are **derived from `scripts/mutants-accepted.txt`, not transcribed** (docs/9's
# derived-population rule). A survivor list built out of the shipped register must classify
# clean; if this file's reading of the register ever drifts from the floor's — a comment
# convention, a whitespace rule — the clean fixture stops classifying clean and this
# predicate goes red, which is the drift being caught rather than hidden.
#
# ## The two seams
#
#   $WCH_GATE_MUTATION_FLOOR   the floor-shaped program to drive. `pass_case` leaves it
#                              unset, which is the real `scripts/mutants.sh`; the failing
#                              arms point it at floors that get exactly one of the three
#                              outcomes wrong.
#   $WCH_GATE_PHASE_RUNNER     the phase-gate runner to drive. Because a fix that stopped at
#                              the floor would only have moved the ambiguity out one layer:
#                              `phase.sh` renders a failing `command` row, and if it renders
#                              all three answers as `FAIL … criterion N failed`, the reader
#                              of `just gate-g4` is back where N66 left them.
#
# Each fixture directory carries a one-word `kind` file. The shipped floor never reads it —
# it has to work out what it is looking at — and it is there for the stub floors in the case
# file, so that each of them can be wrong in exactly one way instead of wrong at everything.
set -euo pipefail

# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

root="$(gate_root)"
# The scripts under test come from the real checkout, not from `gate_root`: a scratch copy
# of the tree has no `.git`, and half of what is proved here is about a git working tree.
# The seams above replace either program wholesale when an arm wants a different one.
checkout="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
floor="${WCH_GATE_MUTATION_FLOOR:-$checkout/scripts/mutants.sh}"
phase_runner="${WCH_GATE_PHASE_RUNNER:-$checkout/scripts/gates/phase.sh}"
accepted_file="$root/scripts/mutants-accepted.txt"

if [[ ! -x "$floor" ]]; then
    gate_fail "$floor is not an executable program; this gate has no floor to drive"
    gate_finish
fi
if [[ ! -x "$phase_runner" ]]; then
    gate_fail "$phase_runner is not an executable program; this gate has no phase runner to drive"
    gate_finish
fi
if [[ ! -f "$accepted_file" ]]; then
    gate_fail "no acceptance register at $accepted_file; the fixtures below are derived from it"
    gate_finish
fi
gate_note "driving $floor and $phase_runner"

scratch="$(mktemp -d "$(gate_scratch_root)/wch-mutation-verdict.XXXXXXXX")"
trap 'rm -rf "$scratch"' EXIT

# ------------------------------------------------------------------ the fixtures
#
# The register, normalised the way the floor normalises it: comments off, trailing
# whitespace off, blank lines out.
register="$scratch/register.txt"
sed 's/#.*//' "$accepted_file" | sed 's/[[:space:]]*$//' | grep -v '^$' >"$register" || true
register_lines="$(grep -c '' <"$register" || true)"
gate_require_nonzero "${register_lines:-0}" "recorded acceptances to derive fixtures from"
if ((register_lines == 0)); then
    gate_finish
fi

# Two mutants that were caught, so a fixture is not all survivors: a result set with an
# empty `caught.txt` is not a shape any real run produces, and a fixture that cannot happen
# proves less than one that did.
caught_rows=$'crates/engine/src/sweep.rs:118:23: replace > with >= in plan_for\ncrates/imaging/src/metrics.rs:96:9: replace / with * in variance'

# A fixture directory: every recorded acceptance, surviving, judged against the register it
# was derived from. Every other fixture below is this one with one thing changed, so each
# claim is about that one thing.
#
# The `:7:5:` is the `line:col` cargo-mutants writes and `mutants.sh` strips before
# comparing — a position that is deliberately not where any of these mutants really sits,
# because an acceptance keyed to a line number would have stopped matching the day somebody
# edited above it, and this fixture proves the stripping still happens.
new_fixture() {
    local kind="$1"
    local dir="$scratch/$kind"
    mkdir -p "$dir"
    printf '%s\n' "$kind" >"$dir/kind"
    cp "$register" "$dir/accepted.txt"
    sed 's|^\([^:]*\.rs\): |\1:7:5: |' "$register" >"$dir/missed.txt"
    printf '%s\n' "$caught_rows" >"$dir/caught.txt"
    : >"$dir/timeout.txt"
    : >"$dir/unviable.txt"
    printf '%s\n' "$dir"
}

clean="$(new_fixture clean)"

# A survivor nobody accepted: the missing test this whole job exists to find.
unaccepted="$(new_fixture unaccepted)"
printf 'crates/engine/src/pairing.rs:44:9: replace && with || in plan\n' >>"$unaccepted/missed.txt"

# The register's second direction: an acceptance that no longer survives.
stale="$(new_fixture stale)"
sed -i '1d' "$stale/missed.txt"

# A result set with rows missing — the shape N66's run left behind when the filesystem
# filled at 23 of 525. The summary describes a run; the rows describe part of one.
truncated="$(new_fixture truncated)"
head -n 3 "$truncated/missed.txt" >"$truncated/missed.txt.part"
mv "$truncated/missed.txt.part" "$truncated/missed.txt"
printf '{"total_mutants":%s,"caught":2,"missed":%s,"timeout":0,"unviable":0}\n' \
    "$((register_lines + 2))" "$register_lines" >"$truncated/outcomes.json"

# No result set at all: a run that was stopped before it wrote one.
absent="$scratch/absent"
mkdir -p "$absent"
printf 'absent\n' >"$absent/kind"
cp "$register" "$absent/accepted.txt"

# ------------------------------------------------------------------ driving the floor

last_output=""

# Run the floor over one fixture, with any extra environment the caller names. Its exit
# status is the subject, so it is captured rather than allowed to abort this script.
run_floor() {
    local dir="$1" status=0
    shift
    last_output="$(env "$@" WCH_MUTANTS_CLASSIFY="$dir" "$floor" 2>&1)" || status=$?
    return "$status"
}

outcomes=0

# Does $2 use the word $1 as a *word*? A substring test is not good enough here and that
# was measured rather than anticipated: the floor's no-verdict trailer names its exit code
# as `EX_TEMPFAIL`, and a substring test read that as the floor calling itself a failure.
# The boundary is "not an upper-case letter or underscore", which is exactly the alphabet
# these tokens are spelled in.
says_word() {
    grep -qE "(^|[^A-Z_])$1([^A-Z_]|\$)" <<<"$2"
}

# Assert the floor answers one fixture with one of the three outcomes — in its exit code
# *and* in its words. Both halves matter: the exit code is what `phase.sh` reads and the
# words are what a person reads, and N66's run got the words wrong while getting the exit
# status non-zero, which is how fifteen minutes of disk failure came to be read as three
# missing tests.
expect_outcome() {
    local want="$1" label="$2" dir="$3" status=0 code want_word forbid_word
    shift 3
    case "$want" in
    green) code=0 want_word="" forbid_word="FAIL" ;;
    finding) code=1 want_word="FAIL" forbid_word="NO VERDICT" ;;
    no-verdict) code="$GATE_NO_VERDICT" want_word="NO VERDICT" forbid_word="FAIL" ;;
    *)
        gate_fail "this gate asked for an outcome called '$want', which is not one of the three"
        return 0
        ;;
    esac

    run_floor "$dir" "$@" || status=$?
    outcomes=$((outcomes + 1))

    if ((status != code)); then
        gate_fail "$label: the floor exited $status where '$want' is exit $code — the three outcomes are only distinct if the exit codes are"
        printf '%s\n' "$last_output" | sed 's/^/        /' >&2
        return 0
    fi
    if [[ -n "$want_word" ]] && ! says_word "$want_word" "$last_output"; then
        gate_fail "$label: the floor exited $status but never said '$want_word'; an exit code nobody reads is not a report"
        printf '%s\n' "$last_output" | sed 's/^/        /' >&2
        return 0
    fi
    if says_word "$forbid_word" "$last_output"; then
        gate_fail "$label: the floor's report says '$forbid_word', which is the vocabulary of a different outcome; this is exactly how N66's disk failure came to be read as a finding"
        printf '%s\n' "$last_output" | sed 's/^/        /' >&2
        return 0
    fi
    gate_note "$label: $want, exit $status"
}

# ------------------------------------------------------------------ claim 1
#
# The three outcomes, over recorded result sets. Seconds, not forty minutes.

expect_outcome green "a register clean in both directions" "$clean"
expect_outcome finding "a survivor with no recorded acceptance" "$unaccepted"
expect_outcome finding "a recorded acceptance that no longer survives" "$stale"
expect_outcome no-verdict "a result set whose rows and summary disagree" "$truncated"
expect_outcome no-verdict "a run that left no result set at all" "$absent"

gate_checked "$outcomes" "recorded result sets classified by the shipped floor as green, a finding, or no verdict"
gate_require_nonzero "$outcomes" "classified result sets"

# ------------------------------------------------------------------ claim 2
#
# The floor notices its own input moving. This is N68 itself: the floor reads the working
# tree for the better part of an hour, and a result describes the tree it read. A fixture
# carries the tree state its run started from (`tree-before.txt`), which is the only way to
# exercise this without editing somebody's checkout — a thing no gate here may do.
#
# The recorded state is the *current* one plus one more modified file, so the arm works on a
# clean tree and on the dirty tree of whoever is writing a fix. The direction is
# deliberately the awkward one: what moved is that a file which was modified when the run
# started is not modified now, which is a reverted edit rather than a new one. The floor has
# no business ranking those.
moved_checked=0
if gate_tree_watchable "$checkout"; then
    moved="$(new_fixture moved)"
    {
        gate_tree_state "$checkout"
        printf ' M crates/engine/src/calibrate.rs\n'
    } >"$moved/tree-before.txt"

    expect_outcome no-verdict "a tree that moved while the floor was reading it" "$moved"
    if [[ "$last_output" != *"crates/engine/src/calibrate.rs"* ]]; then
        gate_fail "the floor reported a moved tree without naming what moved; 'which files' is a reader's first question and the porcelain lines are the answer"
        printf '%s\n' "$last_output" | sed 's/^/        /' >&2
    fi
    moved_checked=1
    gate_checked 1 "run(s) whose recorded tree state no longer matches the tree, reported as no verdict and naming the file"

    # And the other direction of the same check, which is the one that decides whether it is
    # usable: an unchanged tree must not produce a no-verdict. Without this the whole check
    # could be `always refuse`, which is a gate that cries wolf on every run — precisely
    # what N60 says costs a suite its credibility. `clean` carries no `tree-before.txt`, so
    # the floor records the state itself and compares it with what it finds afterwards.
    expect_outcome green "a tree that did not move" "$clean"
    gate_checked 1 "run(s) over an unchanged tree, which must not be refused"
else
    gate_skip 1 "git cannot describe $checkout, so a tree state could not be recorded and 'the floor notices its input moving' was not checked here"
fi

# ------------------------------------------------------------------ claim 3
#
# A tree git cannot describe skips the check, named and counted, and still reaches a
# verdict. A missing tool is not a violation (AGENTS.md rule 3), and a floor that refused to
# classify without git would have turned a source tarball into a permanent no-verdict.
expect_outcome green "a tree git cannot describe" "$clean" GIT_DIR=/nonexistent/wch-no-such-git
if [[ "$last_output" != *"SKIP"* ]]; then
    gate_fail "the floor skipped the tree check without saying so; a skip that is not named and counted reads as a pass (AGENTS.md rule 3)"
    printf '%s\n' "$last_output" | sed 's/^/        /' >&2
fi
gate_checked 1 "run(s) on a tree git cannot describe, which must classify anyway and name the skip"

# ------------------------------------------------------------------ claim 4
#
# The distinction survives the phase gate. `phase.sh` is what `just gate-g4` runs and its
# summary line is what a person actually reads; a floor that distinguishes three outcomes
# under a runner that flattens them back to two has moved the ambiguity one layer out, which
# is not a fix.
#
# Driven over a throw-away criteria table in a scratch root — the real `phase.sh`, the real
# `gate_root` seam, two rows that do nothing but exit. The shipped `phase-criteria.tsv` is
# not touched and no criterion of any real phase is run.
phase_root="$scratch/phase-root"
mkdir -p "$phase_root/scripts/gates"
phase_table="$phase_root/scripts/gates/phase-criteria.tsv"
finding_row=$'gz\tcommand\texit 1\ta criterion that reports a finding'
no_verdict_row="$(printf 'gz\tcommand\texit %s\ta criterion that could not answer' "$GATE_NO_VERDICT")"

phase_out=""
run_phase() {
    local status=0
    printf '%s\n' "$@" >"$phase_table"
    phase_out="$(WCH_GATE_ROOT="$phase_root" "$phase_runner" gz 2>&1)" || status=$?
    return "$status"
}

expect_phase() {
    local want="$1" label="$2" status=0
    shift 2
    run_phase "$@" || status=$?
    if ((status != want)); then
        gate_fail "$label: the phase runner exited $status, wanted $want; the floor's three outcomes are only worth having if the gate that runs it carries them out to its caller"
        printf '%s\n' "$phase_out" | sed 's/^/        /' >&2
        return 1
    fi
    return 0
}

phase_rows=0

if expect_phase 1 "a phase whose criterion reported a finding" "$finding_row"; then
    if says_word "NO VERDICT" "$phase_out"; then
        gate_fail "the phase runner called a finding a no-verdict"
        printf '%s\n' "$phase_out" | sed 's/^/        /' >&2
    fi
    phase_rows=$((phase_rows + 1))
fi

if expect_phase "$GATE_NO_VERDICT" "a phase whose criterion could not answer" "$no_verdict_row"; then
    if ! says_word "NO VERDICT" "$phase_out"; then
        gate_fail "the phase runner did not say 'NO VERDICT' for a criterion that could not answer; its summary line is what a reader of \`just gate-g4\` sees"
        printf '%s\n' "$phase_out" | sed 's/^/        /' >&2
    fi
    if says_word FAIL "$phase_out"; then
        gate_fail "the phase runner reported a criterion that could not answer as FAIL, which is the word a real survivor gets; that is the ambiguity moved one layer out rather than removed (notes N66, N68)"
        printf '%s\n' "$phase_out" | sed 's/^/        /' >&2
    fi
    if [[ "$phase_out" != *"a criterion that could not answer"* ]]; then
        gate_fail "the phase runner never named the row it was given, so nothing above proves the row ran at all"
        printf '%s\n' "$phase_out" | sed 's/^/        /' >&2
    fi
    phase_rows=$((phase_rows + 1))
fi

# Both together, and a finding outranks: a phase that found something and also failed to
# answer something else has found something, and that is the word to end on.
if expect_phase 1 "a phase with one of each" "$no_verdict_row" "$finding_row"; then
    if ! says_word "NO VERDICT" "$phase_out" || ! says_word FAIL "$phase_out"; then
        gate_fail "a phase with one row of each kind reported only one of them; both happened and both belong in the output"
        printf '%s\n' "$phase_out" | sed 's/^/        /' >&2
    fi
    phase_rows=$((phase_rows + 1))
fi

gate_checked "$phase_rows" "phase-gate run(s) proving a no-verdict criterion is rendered and exited differently from a finding"
gate_require_nonzero "$phase_rows" "phase-gate runs"
gate_note "the tree-move claim was exercised $moved_checked time(s)"

# ------------------------------------------------------------------ claim 5
#
# The full floor refuses to start on work that exists only on this machine, and the triage mode
# does not — the owner's ruling of 2026-08-21, whose reasoning `scripts/mutants.sh`'s header
# carries. It comes after the phase claim because it is a different question about the same
# program: claims 1 to 4 are about the verdict a run produced, and this one is about whether the
# run may begin at all.
#
# **The subject makes this the one claim that cannot be driven through $WCH_MUTANTS_CLASSIFY**,
# because a recorded result set is exactly the mode that never asks. So the fixture here is a
# whole (tiny) git repository, with the floor under test installed at `scripts/mutants.sh`
# inside it — which is where the floor resolves its own tree from, `git -C "$here"` rather than
# `$PWD`, so a fixture repository is the only honest way to hand it a tree whose state this arm
# decides. Three of them, differing in one fact each: committed and on a remote, committed and
# on no remote, on a remote with uncommitted work beside it.
#
# **And no mutation run may start here, which is the reason for the `cargo` shim.** A floor that
# passes the precondition goes on to list the scope, and on a machine with cargo-mutants
# installed that is the first minute of an hours-long job — inside a gate that is supposed to
# take seconds. So these runs get a `PATH` whose `cargo` answers `mutants --version` and
# `mutants --list-files` and refuses everything else, and an empty scope is a *finding* the
# shipped floor already has words for. "It started" is therefore read as "it reached the scope
# check and said so", which is a stronger claim than "it did not refuse" and stops one line
# earlier than anything expensive.
preflight_runs=0
if gate_tree_watchable "$checkout"; then
    preflight_bin="$scratch/no-real-cargo"
    mkdir -p "$preflight_bin"
    cat >"$preflight_bin/cargo" <<'SHIM'
#!/usr/bin/env bash
# A `cargo` that can answer the two questions the floor asks before it starts, and nothing
# else. `--list-files` prints no file, so a floor that got past the precondition stops at the
# empty-scope finding rather than beginning a run that takes hours.
set -uo pipefail
if [[ "${1:-}" == "mutants" ]]; then
    case "${2:-}" in
    --version) printf 'cargo-mutants 0.0.0+gate-shim\n'; exit 0 ;;
    --list-files) exit 0 ;;
    esac
fi
printf 'cargo: this gate shim answers only `mutants --version` and `mutants --list-files`; a real mutation run must never begin inside a gate\n' >&2
exit 97
SHIM
    chmod +x "$preflight_bin/cargo"

    # A fixture repository. The identity and the signing flag are given per invocation so that
    # nothing here depends on, or writes to, the person's git configuration.
    #
    #   $1  a name for the directory
    #   $2  the one-word `kind` the stub floors in the case file read — `refuse` for a
    #       repository the shipped floor must not start in, `start` for one it must. The
    #       shipped floor never reads it and works the answer out from git, for the reason
    #       the fixture directories above give.
    #   $3  `on-a-remote` to write the remote-tracking ref a push would have written
    #   $4  `uncommitted` to leave an edit behind after the commit
    new_repo() {
        local kind="$2" remote="$3" left="$4" repo="$scratch/repo-$1"
        mkdir -p "$repo/scripts/gates" "$repo/.cargo"
        cp "$checkout/scripts/gates/lib.sh" "$repo/scripts/gates/lib.sh"
        cp "$floor" "$repo/scripts/mutants.sh"
        chmod +x "$repo/scripts/mutants.sh"
        # Committed, so the floor's own scratch directory does not make this tree dirty and
        # answer the question the arm is asking.
        printf 'target/\n' >"$repo/.gitignore"
        printf '%s\n' "$kind" >"$repo/kind"
        printf '# a scope file, so a refusal here is the precondition and not the missing config\n' \
            >"$repo/.cargo/mutants.toml"
        printf '# an acceptance register with no entries in it\n' >"$repo/scripts/mutants-accepted.txt"
        git -C "$repo" -c init.defaultBranch=main init -q
        git -C "$repo" add -A
        git -C "$repo" \
            -c user.name=gate -c user.email=gate@example.invalid -c commit.gpgsign=false \
            commit -q -m 'the fixture repository this gate hands the floor'
        if [[ "$remote" == "on-a-remote" ]]; then
            # What a push leaves behind, written locally: this suite is offline by
            # construction, and `refs/remotes/…` is exactly the record a push updates.
            git -C "$repo" update-ref refs/remotes/origin/main "$(git -C "$repo" rev-parse HEAD)"
        fi
        if [[ "$left" == "uncommitted" ]]; then
            printf '# an edit nobody committed\n' >>"$repo/scripts/mutants-accepted.txt"
        fi
        printf '%s\n' "$repo"
    }

    pushed="$(new_repo pushed start on-a-remote committed)"
    unpushed="$(new_repo unpushed refuse no-remote committed)"
    dirty="$(new_repo dirty refuse on-a-remote uncommitted)"

    # Run the floor inside a fixture repository. Arguments before `--` are `NAME=value`
    # environment for the run; arguments after it go to the floor. The two variables that
    # decide the subject are cleared first, so a person who exported the escape in their own
    # shell does not quietly turn every refusal below into a pass.
    run_preflight() {
        local repo="$1" status=0 item seen=0
        shift
        local -a envs=() args=()
        for item in "$@"; do
            if ((seen == 1)); then
                args+=("$item")
            elif [[ "$item" == "--" ]]; then
                seen=1
            else
                envs+=("$item")
            fi
        done
        last_output="$(
            env -u WCH_MUTANTS_ALLOW_UNPUSHED -u WCH_MUTANTS_ITERATE -u WCH_MUTANTS_CLASSIFY \
                PATH="$preflight_bin:$PATH" ${envs[@]+"${envs[@]}"} \
                "$repo/scripts/mutants.sh" ${args[@]+"${args[@]}"} 2>&1
        )" || status=$?
        return "$status"
    }

    # `refused` — the floor must not begin: exit $GATE_NO_VERDICT, the word a reader skims for,
    # not the word a survivor gets, and the remedy named. `started` — the floor must begin and
    # be stopped by the shim's empty scope, which is the control this whole claim rests on: a
    # precondition that refused everything would satisfy every `refused` line above it and make
    # the floor unusable, and N60 records what a gate that cries wolf costs.
    expect_preflight() {
        local want="$1" label="$2" repo="$3" status=0 phrase
        shift 3
        run_preflight "$repo" "$@" || status=$?
        preflight_runs=$((preflight_runs + 1))
        case "$want" in
        refused)
            if ((status != GATE_NO_VERDICT)); then
                gate_fail "$label: the floor exited $status where a refusal to start is exit $GATE_NO_VERDICT — a precondition nobody met is not a finding about the code and is not a pass either (owner ruling, 2026-08-21)"
                printf '%s\n' "$last_output" | sed 's/^/        /' >&2
                return 0
            fi
            if ! says_word REFUSED "$last_output"; then
                gate_fail "$label: the floor exited $status without saying REFUSED, which is the word rung-vivid-managed's refusal uses and the word a reader skims for; an exit code nobody reads is not a report"
                printf '%s\n' "$last_output" | sed 's/^/        /' >&2
                return 0
            fi
            if says_word FAIL "$last_output"; then
                gate_fail "$label: the refusal to start says FAIL, which is the word a survivor with no acceptance gets; that is note N66's mistake in a new place"
                printf '%s\n' "$last_output" | sed 's/^/        /' >&2
                return 0
            fi
            for phrase in "commit and push" "just mutants-iterate" "WCH_MUTANTS_ALLOW_UNPUSHED"; do
                if [[ "$last_output" != *"$phrase"* ]]; then
                    gate_fail "$label: the refusal never named '$phrase'; a refusal that does not say what to do next is a wall, and this one has three ways out"
                    printf '%s\n' "$last_output" | sed 's/^/        /' >&2
                    return 0
                fi
            done
            ;;
        started)
            if ((status != 1)); then
                gate_fail "$label: the floor exited $status where a run that started and then met the shim's empty scope is exit 1; this is the case the precondition must let through"
                printf '%s\n' "$last_output" | sed 's/^/        /' >&2
                return 0
            fi
            if says_word REFUSED "$last_output"; then
                gate_fail "$label: the floor refused to start, and this is the case it must not refuse — a floor that refuses everything is the gate that cries wolf (note N60)"
                printf '%s\n' "$last_output" | sed 's/^/        /' >&2
                return 0
            fi
            if [[ "$last_output" != *"mutants.toml"* ]]; then
                gate_fail "$label: the floor exited 1 without naming the scope file, so nothing here shows it got past the precondition rather than stopping somewhere else"
                printf '%s\n' "$last_output" | sed 's/^/        /' >&2
                return 0
            fi
            ;;
        *)
            gate_fail "this gate asked the floor to '$want', which is neither refusing to start nor starting"
            return 0
            ;;
        esac
        gate_note "$label: $want, exit $status"
    }

    expect_preflight refused "a full run whose commit is on no remote" "$unpushed"
    expect_preflight refused "a full run with uncommitted work beside a pushed commit" "$dirty"
    expect_preflight started "a full run on a checkout committed and pushed" "$pushed"
    expect_preflight started "the named escape on a checkout that is on no remote" "$unpushed" \
        WCH_MUTANTS_ALLOW_UNPUSHED=1
    # The escape has two halves and the second is the one a silent environment variable would
    # lose: a deliberate long run on unpushed work stays possible, and it says out loud, counted,
    # what it is accepting. That is the register `WCH_NO_MOTION=1` set for the motor suites, and
    # AGENTS rule 3's "never silence" applied to a precondition somebody turned off.
    if [[ "$last_output" != *"SKIP"* || "$last_output" != *"WCH_MUTANTS_ALLOW_UNPUSHED"* ]]; then
        gate_fail "the escape started the full run without naming itself in a counted skip; an escape nobody can see in the log is the silent environment variable the ruling of 2026-08-21 does not allow"
        printf '%s\n' "$last_output" | sed 's/^/        /' >&2
    fi
    gate_checked 1 "run(s) through the named escape, which must start and must say out loud, counted, what it is accepting"

    expect_preflight started "iterate mode on a checkout that is on no remote" "$unpushed" \
        -- --iterate
    expect_preflight started "iterate mode by its variable, on a checkout that is on no remote" \
        "$unpushed" WCH_MUTANTS_ITERATE=1

    gate_checked "$preflight_runs" "start(s) of the floor over fixture repositories that differ in one fact each — the commit's presence on a remote, the uncommitted work beside it, and the mode asked for"
    gate_require_nonzero "$preflight_runs" "floor starts"
else
    gate_skip 1 "git cannot describe $checkout, so no fixture repository could be built and \"the full run refuses to start on work that exists only on this machine\" was not checked here"
fi

gate_finish
