#!/usr/bin/env bash
#
# Temporary data has one home, it is under `target/`, and a copy of the tree cannot contain
# itself.
#
# **The ruling (owner, 2026-08-12):** "Given the repeated failures coming from tmpfs size
# limits, let's move all the temporary data generated by our tests under a subdirectory of
# `target/`, which is also marked as a cache / temporary directory." Note **N84** records what
# forced it; this predicate is the part of it that can go red.
#
# ## Why this is a gate and not an arm of an existing one
#
# The nearest neighbour is `atomic-write-home.sh` — same shape of claim, "one home, and here is
# the count of everything that bypasses it" — and putting this there was considered and
# refused. That gate's subject is *how a state file is written*: its population is the
# `write_json_atomic` call graph, its arms seed a second `File::create`, and its prose argues
# about `fsync` and `rename`. Where a temporary directory is *made* has no overlap with that
# except the word "one home", and a gate whose subject is two unrelated laws is a gate whose
# failure message has to ask which one you broke. The three other candidates are worse:
# `no-frame-bytes-in-repo.sh` is about content, `testkit-is-dev-only.sh` about a dependency
# edge, `counted-selections.sh` about a table.
#
# It also has a claim neither of those could carry, because it is not a `grep` at all — the
# recursion half below actually copies a tree and looks at what came out.
#
# ## What it checks
#
#   1. **The homes exist and agree.** `gate_scratch_root` and `gate_socket_scratch_root` in
#      `scripts/gates/lib.sh`, `scratch_root` and `SCRATCH_DIR` in `schema::paths`, and
#      `scratch_dir` in `engine::paths`. A gate that only counted violations would be green
#      forever on a tree where the home had been deleted and the literal inlined at every call
#      site — which is the state this repository was in the day before the ruling, at nineteen
#      files. The two languages are also checked to name the *same* directory, read out of
#      `SCRATCH_DIR` rather than transcribed here, because one sweep has to reclaim both.
#
#   2. **Nothing else reaches for the platform's temporary directory.** Every `*.sh` in the
#      tree, and every `*.rs`: no `$TMPDIR`, no `/tmp` literal, no `mktemp` without a
#      directory, no `tempfile::tempdir()`, no `TempDir::new()`, no `Builder::…tempdir()`, no
#      `NamedTempFile::new()`, no `env::temp_dir()`. This is the half that stops the ruling
#      from being undone by habit: the spellings above are what everybody's fingers type.
#
#   3. **A scratch copy contains no `target/` and no nested scratch root.** Not asserted from
#      the source — performed. See "the recursion trap" below.
#
# ## Exemptions are lines, and they are counted out loud
#
# A line preceded by `# wch-scratch-exempt: <reason>` (or `// wch-scratch-exempt: <reason>` in
# Rust) is allowed to say what it says. There are three in the tree and each is an argument
# somebody has to read: the socket root itself, `TempRuntimeDir`'s `sun_path` budget, and the
# line that hands the mutation floor's build root to cargo-mutants through `$TMPDIR` — which
# is all that is left of that exemption since the owner's 2026-08-21 ruling moved the root
# itself under `target/`, where this predicate would have put it anyway. Every one of them is
# printed on every run, with its file, its line and its reason, because an allowlist nobody
# reads is a hole with a nice name.
#
# ## Honest limits
#
#   - This sees spellings, not semantics. A script that assigned `d=/t''mp` or a test that
#     reached `std::env::var("TMPDIR")` by hand is invisible here — the second is why claim 1
#     exists, and review carries the rest.
#   - Prose does not count, in both languages and for `gate_product_lines`'s reason: what
#     defends this rule is the argument written beside it, and those arguments name the very
#     spellings matched on. In shell that means a line whose first non-blank character is `#`;
#     inline trailing comments in shell are *not* stripped, because `${x#y}` is not a comment
#     and a rule that has to know is a rule that needs a parser.
set -euo pipefail

# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

root="$(gate_root)"

# The two files in the tree that hold every forbidden spelling on purpose: this predicate,
# which has to match on them, and its own case file, whose arms write them into a copy of a
# script to prove this goes red. Both are derived from `$0` and from the harness's own
# `<gates>/cases/<name>.cases.sh` convention rather than written down, so a rename follows.
#
# It is a hole and it is the smallest one available: a genuine second reach for `$TMPDIR`
# hidden in the case file that exists to seed second reaches would be invisible here. The
# alternative was an exemption marker on each of the four seeding lines, which buys the same
# blindness one line at a time and prints four notes on every CI run to say so.
self_dir="$(cd "$(dirname "$0")" && pwd)"
self_name="$(basename "$0" .sh)"
checkout="$(gate_checkout)"
self_rel="${self_dir}/${self_name}.sh"
self_rel="${self_rel#"$checkout"/}"
self_cases_rel="${self_dir}/cases/${self_name}.cases.sh"
self_cases_rel="${self_cases_rel#"$checkout"/}"

# ------------------------------------------------------------------ claim 1: the homes

lib="$root/scripts/gates/lib.sh"
schema_paths="$root/crates/schema/src/paths.rs"
engine_paths="$root/crates/engine/src/paths.rs"

homes=0
home_missing=0

# `<file>` must define `<definition>`; the description says what is lost if it does not.
require_home() {
    local file="$1" definition="$2" what="$3"
    homes=$((homes + 1))
    if [[ ! -f "$file" ]]; then
        gate_fail "${file#"$root"/} is missing; $what has no home"
        home_missing=1
        return
    fi
    if ! grep -Eq -- "$definition" "$file"; then
        gate_fail "${file#"$root"/} no longer defines $definition; $what has no home, and claim 2 below would be counting bypasses of nothing"
        home_missing=1
    fi
}

require_home "$lib" '^gate_scratch_root\(\)' "where a shell script puts temporary data"
require_home "$lib" '^gate_socket_scratch_root\(\)' "where a directory that will hold a Unix socket goes"
require_home "$lib" '^gate_scratch_sweep\(\)' "what reclaims scratch a killed run abandoned"
require_home "$schema_paths" '^pub fn scratch_root\(\)' "where Rust puts temporary data"
require_home "$schema_paths" '^pub const SCRATCH_DIR' "the name the two languages have to agree on"
require_home "$engine_paths" '^pub fn scratch_dir\(\)' "the one constructor for a scratch directory in Rust"

gate_checked "$homes" "declarations of where temporary data goes"
gate_require_nonzero "$homes" "homes"

# The two languages name one directory. Read out of the Rust constant, so this cannot drift
# into a check that both sides spell whatever this file happens to say.
if ((home_missing == 0)); then
    scratch_dir_name="$(sed -n 's/^pub const SCRATCH_DIR: &str = "\([^"]*\)".*/\1/p' "$schema_paths")"
    if [[ -z "$scratch_dir_name" ]]; then
        gate_fail "could not read SCRATCH_DIR out of crates/schema/src/paths.rs; the agreement below cannot be checked"
    elif ! grep -q "target/$scratch_dir_name" "$lib"; then
        gate_fail "schema::paths::SCRATCH_DIR is \"$scratch_dir_name\" but scripts/gates/lib.sh does not name target/$scratch_dir_name; two scratch roots is one sweep that reclaims half of them"
    else
        gate_checked 1 "agreement between the shell root and the Rust root on target/$scratch_dir_name"
    fi
fi

# ------------------------------------------------------------ claim 2: no second reach

# Print `<line number>\t<line>` for every line of $1 that matches the extended regex $2,
# skipping prose and honouring the exemption marker.
#
#   $3  the comment introducer: `#` for shell (whole-line comments only) or `//` for Rust
#       (everything from the marker to end of line, `gate_product_lines`'s rule)
offending_lines() {
    awk -v pattern="$2" -v style="$3" '
        {
            raw = $0
            code = raw
            if (style == "//") { sub(/\/\/.*/, "", code) }
            else if (raw ~ /^[[:space:]]*#/) { code = "" }

            if (exempt) { exempt = 0; next }
            if (raw ~ /wch-scratch-exempt:/) { exempt = 1; next }
            if (code ~ pattern) { printf "%d\t%s\n", FNR, raw }
        }
    ' "$1"
}

# Every exemption in the tree, one line each: where it is and what it says for itself.
report_exemptions() {
    local file="$1" rel="${1#"$root"/}"
    { grep -n 'wch-scratch-exempt:' "$file" || true; } |
        sed "s|^\([0-9]*\):.*wch-scratch-exempt: *|exemption at $rel:\1 — |"
}

# `mktemp` with no directory in its template falls back to the platform's temporary
# directory, which is the thing the ruling moved away from. Matched by hand rather than by
# regex because "the argument list after the word contains a slash" is not a thing a regex
# says well.
mktemp_without_a_directory() {
    awk '
        {
            raw = $0
            if (raw ~ /^[[:space:]]*#/) { next }
            if (exempt) { exempt = 0; next }
            if (raw ~ /wch-scratch-exempt:/) { exempt = 1; next }
            at = index(raw, "mktemp")
            if (at == 0) { next }
            if (index(substr(raw, at + 6), "/") == 0) { printf "%d\t%s\n", FNR, raw }
        }
    ' "$1"
}

# Bracket expressions rather than backslash escapes: these travel into `awk` through `-v`,
# which processes escape sequences in the value, so a `\(` would arrive as something else.
shell_pattern='TMPDIR|/tmp([/"'"'"']|$)'
rust_pattern='tempfile::tempdir[(]|TempDir::new[(]|[.]tempdir[(][)]|[.]tempfile[(][)]|NamedTempFile::new[(]|temp_dir[(][)]'

shell_files=0
exemptions=0
while IFS= read -r -d '' file; do
    rel="${file#"$root"/}"
    if [[ "$rel" == "$self_rel" || "$rel" == "$self_cases_rel" ]]; then
        continue
    fi
    shell_files=$((shell_files + 1))
    while IFS=$'\t' read -r number line; do
        gate_fail "$rel:$number reaches for the platform's temporary directory ($line); temporary data has one home, gate_scratch_root, and a socket's directory has the other, gate_socket_scratch_root (owner ruling 2026-08-12, note N84)"
    done < <(offending_lines "$file" "$shell_pattern" '#')
    while IFS=$'\t' read -r number line; do
        gate_fail "$rel:$number calls mktemp with no directory in its template ($line), which lands in \$TMPDIR; give it \"\$(gate_scratch_root)/wch-….XXXXXXXX\""
    done < <(mktemp_without_a_directory "$file")
    while IFS= read -r note; do
        gate_note "$note"
        exemptions=$((exemptions + 1))
    done < <(report_exemptions "$file")
done < <(gate_find "$root" -name '*.sh')

gate_checked "$shell_files" "shell scripts checked for a second way to reach \$TMPDIR"
gate_require_nonzero "$shell_files" "shell scripts"

rust_files=0
while IFS= read -r -d '' file; do
    rel="${file#"$root"/}"
    rust_files=$((rust_files + 1))
    while IFS=$'\t' read -r number line; do
        gate_fail "$rel:$number makes a temporary directory outside the one home ($line); use engine::paths::scratch_dir(), or tempfile's *_in constructors over schema::paths::scratch_root() (owner ruling 2026-08-12, note N84)"
    done < <(offending_lines "$file" "$rust_pattern" '//')
    while IFS= read -r note; do
        gate_note "$note"
        exemptions=$((exemptions + 1))
    done < <(report_exemptions "$file")
done < <(gate_rust_files)

gate_checked "$rust_files" "Rust source files checked for a temporary directory outside the one home"
gate_require_nonzero "$rust_files" "Rust source files"
gate_checked "$exemptions" "named exemptions, each printed above with its reason"

# --------------------------------------------------------- claim 3: the recursion trap
#
# `--exclude=target` in `gate_scratch_tree` used to be an optimisation — the tree minus
# `.git` and `target` is 46 MB and `target/` alone is 233 GB — and since the ruling put the
# destination *inside* the source it is what stops a copy from containing itself. Nothing
# tested it, in either job.
#
# **The dynamic half is a real copy of a real tree**, and the tree is synthetic for one
# reason: it has to contain a `target/` with something in it, and it has to have the scratch
# root inside it, so that both failure modes are reachable at all. The checkout's own copy
# would prove the first and not the second (its scratch root is the real one, not one that
# `tar` would walk into). It is bounded — a handful of files — which the alternative is not.
#
# **The static half is why an ordinary `sed` cannot get past this gate.** The honest dynamic
# test for "the exclusion was deleted" is to run the shipped copier without it and see what
# happens, and what happens — measured on a synthetic tree, recorded beside the copier — is
# 233 GB copied into the tree, plus a nested copy of the place copies go whose depth is a race
# rather than a constant. A gate does not get to perform the defect it checks for, so the
# removal is caught by reading the copier in the tree under test — which is exactly the thing a
# selftest arm can seed.

trap_claims=0
synthetic="$(mktemp -d "$(gate_scratch_root)/wch-recursion.XXXXXXXX")"
trap 'rm -rf "$synthetic"' EXIT

mkdir -p "$synthetic/crates/thing/src" "$synthetic/target/deps"
printf 'a tree\n' >"$synthetic/README.md"
printf 'fn main() {}\n' >"$synthetic/crates/thing/src/lib.rs"
printf 'build output nobody should copy\n' >"$synthetic/target/deps/artifact.o"

copy=""
if ! copy="$(
    export WCH_GATE_ROOT="$synthetic"
    export WCH_GATE_SCRATCH="$synthetic/target/wch-scratch"
    gate_scratch_tree
)"; then
    gate_fail "gate_scratch_tree could not copy a synthetic tree; the recursion claim below proved nothing"
    copy=""
fi

if [[ -n "$copy" && -d "$copy" ]]; then
    trap_claims=$((trap_claims + 1))
    if [[ ! -f "$copy/README.md" || ! -f "$copy/crates/thing/src/lib.rs" ]]; then
        gate_fail "a scratch copy of a two-file tree is missing its files; this claim would be true of an empty directory, which is the one way it must not pass"
    fi

    trap_claims=$((trap_claims + 1))
    if [[ -e "$copy/target" ]]; then
        gate_fail "a scratch copy contains target/; with the destination inside the source that is 233 GB copied into the tree per arm, and it is the word that stops the copy from containing the place copies go"
    fi

    trap_claims=$((trap_claims + 1))
    # `-mindepth 1`, because the copy's own directory is itself named `wch-tree.…` and a
    # search that started by finding its own starting point would be red on every tree.
    nested="$(find "$copy" -mindepth 1 \( -name 'wch-scratch' -o -name 'wch-tree.*' \) | head -n 5)"
    if [[ -n "$nested" ]]; then
        gate_fail "a scratch copy contains a nested scratch root ($nested); the copy is copying the place copies go"
    fi

    trap_claims=$((trap_claims + 1))
    if [[ "$copy" != "$synthetic/target/wch-scratch/"* ]]; then
        gate_fail "gate_scratch_tree put its copy at $copy, which is not under the scratch root it was given; the ruling is that temporary data lives under target/"
    fi
fi

# The static half: the copier *in the tree under test* still names both exclusions.
trap_claims=$((trap_claims + 1))
if [[ ! -f "$lib" ]]; then
    gate_fail "scripts/gates/lib.sh is missing; the copier cannot be read"
else
    copier="$(awk '/^gate_scratch_tree\(\)/, /^}/' "$lib")"
    if [[ -z "$copier" ]]; then
        gate_fail "scripts/gates/lib.sh no longer defines gate_scratch_tree; nothing here knows how a scratch copy is made"
    else
        # Three exclusions, three different things lost, so three messages rather than a loop
        # with one sentence that would have to be vague enough to cover all of them.
        if ! grep -Fq -- '--exclude=target' <<<"$copier"; then
            gate_fail "gate_scratch_tree no longer excludes target/; since the ruling put the destination inside the source this is not the size optimisation it was written as — measured, a copier without it puts 233 GB into the tree per arm, at around two hundred arms a run"
        fi
        if ! grep -Fq -- '--exclude=.git' <<<"$copier"; then
            gate_fail "gate_scratch_tree no longer excludes .git; a scratch copy that carries the object store is a copy whose size is the repository's whole history"
        fi
        if ! grep -Fq 'excludes+=(--exclude=' <<<"$copier"; then
            gate_fail "gate_scratch_tree no longer derives an exclusion for the scratch root it is copying into; that line is the one that stops a copy from containing the place copies go — measured, with it gone as well a copy comes out holding a nested target/wch-scratch/wch-tree.… of itself"
        fi
    fi
fi

gate_checked "$trap_claims" "properties of a scratch copy and of the copier that makes it"
gate_require_nonzero "$trap_claims" "properties of a scratch copy"

gate_finish
